### ISSUE TITLE
Header Background

### ISSUE THREAD

**Issue by IanWONeill** [beatmasterRS/skin.arctic.zephyr.mod#1]
When I want to hide the Header the Background is persistent and I can't seem to figure out how to remove it.

The 'Home' etc, Icons and Media counts are removed but the White Background (Light theme) is just in the way afterwards.

Any ideas on how I can go about removing this?

![image](https://user-images.githubusercontent.com/20154372/51510194-f66b5b00-1df3-11e9-8285-39f28a114344.png)

**Comment by beatmasterRS** [comment]
Unfortunately I can't reproduce the error in my case. Which settings do you have? Maybe you have screenshots of your settings to? Have you downloaded the latest version? 

https://github.com/beatmasterRS/skin.arctic.zephyr.mod/archive/master.zip

**Comment by beatmasterRS** [comment]
Unfortunately I can't reproduce the error in my case. 

![screenshot437](https://user-images.githubusercontent.com/3855273/51519922-8fb16600-1e22-11e9-8522-f0ec783b8207.png)

Which settings do you have? Maybe you have screenshots of your settings too? Have you downloaded the 
[latest version](https://github.com/beatmasterRS/skin.arctic.zephyr.mod/archive/master.zip)?

**Comment by IanWONeill** [comment]
Hmmm odd, I am using the latest as of Yesterday however I will merge the Changes from today to see if it has any effect though I'm doubtful due to there being no substantial commit ( afaik ) to do with modifying the header area.

**Comment by beatmasterRS** [comment]
To be honest, I'm a bit baffled right now. Which kodi version do you use?

The header background-images are included in [includes_home.xml](https://github.com/beatmasterRS/skin.arctic.zephyr.mod/blob/master/1080i/Includes_Home.xml) on lines 11 - 31.

**Comment by IanWONeill** [comment]
I'm using 18rc5.

I attempted to play around with the HomeHeader include but still nothing - it's driving me mad.
`    <include name="HomeHeader">
        
        <control type="group">
            <visible>Skin.HasSetting(home.showheader)</visible>
            
            <animation effect="slide" start="0" end="0,-250" time="150" condition="[!Skin.HasSetting(home.classicwidgets) + Control.HasFocus(301)]">Conditional</animation>
            <animation effect="slide" start="0" end="0,-250" time="150">WindowClose</animation>
            <animation effect="slide" end="0" start="0,-250" time="150">WindowOpen</animation>
            <control type="image" description="TopBG">
                <width>100%</width>
                <top>0</top>
                <height>240</height>
                <aspectratio aligny="top">scale</aspectratio>
                <texture colordiffuse="Background">common/bg.jpg</texture>
                <animation effect="fade" start="100" end="75" time="200" condition="true">Conditional</animation>
            </control>
            <control type="image" description="FanartOverlay">
                <width>100%</width>
                <height>240</height>
                <top>0</top>
                <aspectratio aligny="bottom">scale</aspectratio>
                <texture colordiffuse="FloorFade2">common/floor.png</texture>
            </control>
            <control type="image" description="Shadow">
                <width>100%</width>
                <height>16</height>
                <top>240</top>
                <texture flipy="false">common/shadow16B.png</texture>
            </control>
            <include>Furniture_Header</include>
            <control type="group">
                <visible>Player.HasMedia</visible>
                <include>Animation.FadeIn</include>
                <include>Animation.FadeOut</include>
                <include>Furniture_NowPlaying</include>
            </control>
        </control>
    </include>`

I assumed it would be something to do with this part
`            <control type="image" description="TopBG">
                <width>100%</width>
                <top>0</top>
                <height>240</height>
                <aspectratio aligny="top">scale</aspectratio>
                <texture colordiffuse="Background">common/bg.jpg</texture>
                <animation effect="fade" start="100" end="75" time="200" condition="true">Conditional</animation>
            </control>`
The TopBG control - however even just straight up removing this XML does nothing.

**Comment by beatmasterRS** [comment]
Try to remove all lines from 11- 31, save the file and restart kodi for changes to take effect.

**Comment by IanWONeill** [comment]
Worked, weird work-around hmm.

Thanks regardless 👍
