### ISSUE TITLE
Font.xml

### ISSUE THREAD

**Issue by hidalgo67** [beatmasterRS/skin.arctic.zephyr.mod#100]
I don’t know how to create a pull request, so I try it here. I just add a fontset to your Font.xml, so the complete file will look like

[Font.xml.zip](https://github.com/beatmasterRS/skin.arctic.zephyr.mod/files/6067940/Font.xml.zip)
[Assistant.zip](https://github.com/beatmasterRS/skin.arctic.zephyr.mod/files/6067941/Assistant.zip)

**Comment by beatmasterRS** [comment]
Has been added in the latest version.
