### ISSUE TITLE
[ISSUE] - theme no supported by Kodi 21.1

### ISSUE THREAD

**Issue by smoonlee** [beatmasterRS/skin.arctic.zephyr.mod#1094]
Just updated my Raspberry Pi 4B running OSMC 2024-08-01 and can no longer use the theme 🥲 If you need any logs or config let me know.

**Comment by wietze** [comment]
I got this message too, but downloading the latest version for Omega from the releases section ([link](https://github.com/beatmasterRS/skin.arctic.zephyr.mod/archive/master.zip)) and installing it from ZIP allowed to get it to work. It kept all settings too.
