### ISSUE TITLE
Option to remove Play/Pause circle

### ISSUE THREAD

**Issue by tomatosoupcan** [beatmasterRS/skin.arctic.zephyr.mod#11]
Would it be possible to get an option to remove the Play/Pause circle that appears when a video is paused? Seems a new addition between the original and the mod and I'm not a huge fan of it visually. Right now I am doing this manually every time the skin updates by commenting out the lines in Includes_OSD.xml but it would be great if this was a toggleable option somewhere in the settings.

**Comment by beatmasterRS** [comment]
No problem, will be added with the next update.

**Comment by beatmasterRS** [comment]
It's added in https://github.com/beatmasterRS/skin.arctic.zephyr.mod/commit/38ea50e3cb08bcf0e3073f365ef64e6978b91d5c 
and will rolled out with next release :)

**Comment by tomatosoupcan** [comment]
Thanks!
