### ISSUE TITLE
Playlist are not displayed for use in widgets

### ISSUE THREAD

**Issue by tteichma** [beatmasterRS/skin.arctic.zephyr.mod#111]
I have a set of smart playlist containing a set of movies (e.g. featue films, documentaries, stuff from youtube, ...).

I am trying to configure the main menu in such a way that each tab is connected to one of these playlists, opening the playlist when hitting enter and displaying the cover of ten random movies from it.

I would expect to be able to choose this when configuring the main menu by selecting "Action" / "Widget 1" -> "Video Library" -> "Playlist" > $PlaylistTitle. However no entries are displayed in "Playlist". When browsing files, I can see the content of all playlists in "Videos" -> "Playlists" -> $PlaylistTitle.

I had it working somehow in Leia, it only stopped working in Matrix.

I also have this problem with a clean installation of Matrix (~/.kodi/ deleted) and only installing the addons "PlexKodiConnect" and "Arctic: Zephyr - Reloaded" and their respective repositories.

Any advice of why this may not be working and / or how I can fix it?

Thank you!

**Comment by beatmasterRS** [comment]
I have never used this, but I have now been able to reproduce it with your instructions. I used the playlist as widget content, which means that the movies that are in the playlist are displayed in the main menu.

Then I changed the main menu entry and also selected the playlist there. Kodi asks me if I want to play or show the playlist. I selected "show".

So now I have a main menu item that shows me the playlist as a widget and with a click on the homemenu-item, kodi takes me directly to the playlist.

So for me, everything works fine so far.

What is the result or what exactly is not working?

**Comment by tteichma** [comment]
Can you explain, how you manage to use the playlist as widget content?

If I try to set it as written above ("Widget 1" -> "Video Library" -> "Playlist") I expect to see a list of all my video playlists. but I see none.

One level above ("Widget 1" -> "Video Library") I see all the folders added by video sources, but also not the playlists.

**Comment by beatmasterRS** [comment]
Please have a look, how i have done: https://youtu.be/w0HrNdc4a-o

If that doesn't help, you could try to reset the SkinShortcuts configuration to Skin defaults.

**Comment by tteichma** [comment]
Thank you for your support.

I was following the exact same steps, but for me the Playlist entry of the main menu configuration did not contain any elements.

SkinShortcuts was not installed here, so I downloaded it from http://mirrors.kodi.tv/addons/matrix/script.skinshortcuts/script.skinshortcuts-1.1.4.zip.

It still failed then, because this version seems to be incompatible with Python 3.9. This can be fixed by replacing all occurences of `xmldata.getiter()` with `xmldata.iter()` in `addons/script.skinshortcuts/resources/lib/library.py`.

It works as intended now, thank you!

**Comment by beatmasterRS** [comment]
Thanks for feedback :)
