### ISSUE TITLE
Auto update button links to a section incorrectly

### ISSUE THREAD

**Issue by PSTrophy** [beatmasterRS/skin.arctic.zephyr.mod#113]
Small bug when it comes to trying to turn on auto update within the options menu (left on remote) inside settings/add-ons. Instead of it checking the box to enable them it brings you to system/add-ons and does the same when.unchecking it. Also when exiting Kodi and relaunching both auto update and notification check boxes go back to unchecked status when they were checked prior to exit.

**Comment by beatmasterRS** [comment]
Thanks for pointing this sout :) I've fixed it. Its now the same as in estuary.

https://github.com/beatmasterRS/skin.arctic.zephyr.mod/commit/f1e22c193454475a2095694f65dd047145b51835
