### ISSUE TITLE
Weather widget issue

### ISSUE THREAD

**Issue by JC253** [beatmasterRS/skin.arctic.zephyr.mod#116]
Hello beatmasterRS - I'm having problems with the weather widget working properly when widgets are set as Featured. 
Also had a problem when set to Multi-Netflix, say I'd have weather widget set for Power Menu item which would be last in menu bar, the menu item (Addons) widget to the left of Power menu item wont show at all. Switch it to Featured, that menu item (Addons) will show fine, but not the weather widget for Power. Using Gismeteo as weather service btw. Hope all that makes sense. I've attatched two screenshots for reference. This is my first time posting anything on Github, forgive me if I didn't do anything correctly or explained poorly. Thanks for the skin, really liking it alot so far! 

And question - Would it be possible to make a fix, so that if you use the Multi-Netflix style, you're able to press 'down' to get back to your menu position rather than pressing up? I tried the 3 widget fixes included, couldn't get any to do this. Look forward to hearing from you.

![Screenshot (93)](https://user-images.githubusercontent.com/79684237/110450173-cf298380-8077-11eb-9445-69ca14874987.png)

![Screenshot (92)](https://user-images.githubusercontent.com/79684237/110449878-7fe35300-8077-11eb-9a48-b49bc4ab35b4.png)

**Comment by beatmasterRS** [comment]
Can you please test the latest version from here?

https://github.com/beatmasterRS/skin.arctic.zephyr.mod/archive/master.zip

**Comment by beatmasterRS** [comment]
Please force skin shortcuts to rebuilt the menu. 

Methods: 

> reset to skindhortcuts to skin defaults
> change something in your skindhortcuts homemenuconfig

After that, got to the homemenu and let skindhortcuts rebuilt.

Please let me know, if that fixes this behaviour.

**Comment by JC253** [comment]
I've tried this many times. I've used the skin for a public build that is on v1.0 right now. I'm working on 1.1. This has been an issue since I started making the build. I've force refreshed all addons, repos, I've reset the skin to defaults and I've started from scratch 3 times with a fresh kodi and using either your repo or the zip directly. I really don't think there's anything on my end that I can do to make it work. I've tried everything I can think of.

**Comment by beatmasterRS** [comment]
Unfortunately I currently have no more ideas what could cause this behavior...

**Comment by beatmasterRS** [comment]
Could you please provide your script-skinshortcuts-includes.xml file from the addon folder?

**Comment by JC253** [comment]
Do I just copy and paste them here, or do I need to zip them?

**Comment by beatmasterRS** [comment]
You can zip and Upload them on a free filehoster and post the link here.

**Comment by JC253** [comment]
Sorry for such a late reply. Yes, I'll send it after work tonight.

**Comment by JC253** [comment]
https://www.dropbox.com/s/pa4af6d5f10naw8/script-skinshortcuts-includes.zip?dl=0

https://www.dropbox.com/s/5boh003ag6ovgz1/settings.zip?dl=0

**Comment by beatmasterRS** [comment]
I was able to load and test your configuration. But unfortunately I cannot reproduce the behavior you have mentioned. For me, everything works fine with widget navigation.

**Comment by JC253** [comment]
Using Featured widget? It works fine on the others, but featured it doesn't
show at all.

**Comment by beatmasterRS** [comment]
Yes, i did. I've had the same configuration as you.

**Comment by JC253** [comment]
OK well there's definitely an issue. Can I send you the whole zip of the
build after I get home from work tonight so you can see?

**Comment by beatmasterRS** [comment]
Thats ok, no problem.

**Comment by JC253** [comment]
Ok great, thanks alot.
https://www.dropbox.com/s/f5j8tuzc0go82ks/ReloadedV1.2.zip?dl=0

**Comment by beatmasterRS** [comment]
No File to download, cause deleted

**Comment by JC253** [comment]
Whoops. I'll send again after work tonight, sorry.

**Comment by JC253** [comment]
https://www.dropbox.com/s/mbyn16hgwye093w/ReloadedV1.3.zip?dl=0

**Comment by beatmasterRS** [comment]
Sorry, but your folders contain illegal addons and there is no support from me for that. If you have a clean Kodi installation and the problem still occurs, please open a new issue on github, provide your userdata and addon folders and i will take a look.

**Comment by JC253** [comment]
I'm not asking for support from you on the addons. I'm asking for a weather widget fix. How am I supposed to get this issue fixed if you won't look at it? What good would it do me to install a clean Kodi? The issue happens when adding other menu items. Not quite sure what you want me to do here, but I did tell you it was a public build (has "illegal addons")
