### ISSUE TITLE
Main menu widget behavior issue

### ISSUE THREAD

**Issue by so-o-bima** [beatmasterRS/skin.arctic.zephyr.mod#118]
Thank you.
I'm using the best skin.
I am an Android 19.0 version kodi user.
Widgets do not move down in multi-home screen mode.
There is a post on the kodi forum asking to reset and recreate the menu, so I tried the reset.
When I check it, there is no problem until there are 11 menu items.
If the menu item adds more than 12 menu items, the widget doesn't come down.
Please check.

**Comment by beatmasterRS** [comment]
I was able to reproduce this behaviour and hopefully fixed it. 

Could you please test this version here? It is important that you force SkinShortcuts to rebuild after installation. It's enough to change a value in the Skinshortcuts menu (if you don't want to reset completely), then SkinShortcuts will rebuild the menu, when you are in homemenu.

https://github.com/beatmasterRS/skin.arctic.zephyr.mod/archive/widgets-fix-testing.zip

**Comment by so-o-bima** [comment]
Thank you for the quick reply and bugfix from the developer.
I just tested the version given by the link.
Even if the main menu exceeds 12, you can now move the widget up and down.
I respect the developer.
Thank you.
