### ISSUE TITLE
[Query]Similar/Studio etc getting replaced by actual path after some time

### ISSUE THREAD

**Issue by onlytanmoy** [beatmasterRS/skin.arctic.zephyr.mod#123]
Hi mate, please see the video recording- you will notice the section names like Similar/Studio etc they get replaced by the scrolling actual destination, is there a way to stop that? I would like to see the section names as they are like Similar/Studio/YouTube/Artwork etc and not the path url.
https://imgur.com/a/YFQHc25

**Comment by beatmasterRS** [comment]
Try this option:

![screenshot00568](https://user-images.githubusercontent.com/3855273/110530284-90003e80-811a-11eb-9baf-bba5689969fb.png)

This prevents the label from being hidden and the path from being shown.

**Comment by onlytanmoy** [comment]
@beatmasterRS Super! that worked like a charm :) thank you.
Can I just ask how you got this dual colour highlight (two shades of green) on your selection? what exactly I need to do in the colour section of the settings to achieve this please?

**Comment by beatmasterRS** [comment]
Just have a look at the color settings :)

![screenshot00572](https://user-images.githubusercontent.com/3855273/110532313-eec6b780-811c-11eb-83aa-9566755c4d1b.png)

**Comment by onlytanmoy** [comment]
Ahh, gradient settings :) Thanks for the pointer mate 👍
