### ISSUE TITLE
RebootToAndroid

### ISSUE THREAD

**Issue by Thomaskito** [beatmasterRS/skin.arctic.zephyr.mod#124]
Reboot to Android is not working on coreelec 19.
It do not Restart the box automatic like it do on other skins

**Comment by beatmasterRS** [comment]
With what other skins?

**Comment by Thomaskito** [comment]
Aero Nox silvo. 
I hope this can be fixed, this skin looks very good.

**Comment by beatmasterRS** [comment]
Please try to reset the powermenu configuration to skin defaults. Then let skinshortcuts rebuilt the config, when you are in homemenu. In the Powermenu everything is implemented the same as in the AeonNox Silvo:

```
<action>System.ExecWait("/usr/sbin/rebootfromnand")</action>
<action>Reset()</action>
<visible>System.PathExist("/dev/env")</visible>
```

**Comment by Thomaskito** [comment]
I try it. 
But unfortunately still the same AeonNox Silvo: it reboot to Android
skin.arctic.zephyr the power menu just closed en nothing happiness.

**Comment by beatmasterRS** [comment]
Can you send me your skinshortcuts-includes.xml file from the 1080i skin folder please? Then I can take a closer look

**Comment by beatmasterRS** [comment]
This is just a test version to see if it works now.

**Comment by Thomaskito** [comment]
Thanks.
I Will test it this evening our tomorrow in the morning and let you now

**Comment by Thomaskito** [comment]
Now it works.
Now it reboot to Android
Thanks

**Comment by beatmasterRS** [comment]
Okay, will be merged later, thanks for your feedback.
