### ISSUE TITLE
[Feature Request]Edit title of widget

### ISSUE THREAD

**Issue by onlytanmoy** [beatmasterRS/skin.arctic.zephyr.mod#125]
Good morning :) please provide option to rename the widget label, so when I go to customise main menu- widgets, it will allow me to rename the widget title also.
https://imgur.com/a/Xru7tEY

**Comment by PSTrophy** [comment]
I thought you had the option to name them when you first set them up?

**Comment by beatmasterRS** [comment]
I have been looking for a solution, but currently there is no way for me to add a button to rename widgets....

**Comment by PSTrophy** [comment]
Ya big meanie lol.
