### ISSUE TITLE
View type issues

### ISSUE THREAD

**Issue by PSTrophy** [beatmasterRS/skin.arctic.zephyr.mod#128]
I've been trying to set the default view for episodes to shifted more and it's not greyed out and is selectable but as soon as I select it it goes to list view.

BioFX on the Kodi forum also raised a possible issue with Symbols view also. I'll try and confirm.

EDIT: Confirmed. Symbols defaults to Icons for some reason...

**Comment by beatmasterRS** [comment]
Can you describe, what exactly the problem is with the view? Which content type? Thanks :)

**Comment by PSTrophy** [comment]
Not sure I don't think it was mentioned by BioFX I'll test myself. In regards to shifted more the view was episodes only ithink.

**Comment by beatmasterRS** [comment]
> Symbols is selectable for these views:
> Root, movies, TV and TV season list but reverts to Icons view in all of them.

So you mean that you can't use symbols for movies/tvshows/seasons? 

We are talking about the same symbols-view?
![screenshot00584](https://user-images.githubusercontent.com/3855273/110837702-de8c1500-82a1-11eb-8dc1-095ad84f063e.png)


> EDIT: I'll start testing all the other views and see if there are issues after my dinner. Spaghetti Bolognese time.....

:D

**Comment by PSTrophy** [comment]
I'm confused myself tbh. That's what I found with my testing.

**Comment by beatmasterRS** [comment]
Okay, now I still don't know what view we're talking about. Please turn on debugging. At the top left you will see the view-id. Symbols has e.g. the 55. 

![screenshot00588](https://user-images.githubusercontent.com/3855273/110843945-28c4c480-82a9-11eb-85a3-a4c3b25eeadd.png)

![screenshot00590](https://user-images.githubusercontent.com/3855273/110843950-29f5f180-82a9-11eb-8a0c-f47641de1a19.png)

**Comment by beatmasterRS** [comment]
So the symbols-view you mean has which id?

**Comment by beatmasterRS** [comment]
I have to take a closer look at the language strings...

![screenshot00591](https://user-images.githubusercontent.com/3855273/110844525-cddf9d00-82a9-11eb-8203-0af56f11a26a.png)

**Comment by PSTrophy** [comment]
55 is actually Icons according to view options menu.

**Comment by beatmasterRS** [comment]
Then I don't know what "symbols" view you exactly mean....

**Comment by PSTrophy** [comment]
I can't get to the Symbols view at all so narrowing down what view ID it is exactly is the issue. Both pictures you posted are view 55 but according to my debugging 55 is Icons.

**Comment by beatmasterRS** [comment]
The whole view selector has to be reworked and exactly defined, which view is enabled/suitable for which content. This behaviour not only affects the "shifted more" view. As you can see, there are much more views, that are enabled and when the content type is e.g. "files", there should be only the list view enabled. 

The view "shifted more"is only available for the following content types: movies, tvshows, seasons and episodes.

Still much to do ;)

**Comment by PSTrophy** [comment]
Yeah I noticed that a lot of views do that in respect to being selectable but default to list instead. Your going to be busy lol
