### ISSUE TITLE
[Feature Request]Please include Play option for movie

### ISSUE THREAD

**Issue by onlytanmoy** [beatmasterRS/skin.arctic.zephyr.mod#130]
Play option missing for the movie the actor is part of, please see the screen recording
https://imgur.com/a/Jm9hozA

**Comment by beatmasterRS** [comment]
Thats already implemented and provided by embuary.helper, but only available for DB-content. :)

**Comment by onlytanmoy** [comment]
Oh no, not again :( anyway you can implement it for streaming movies? I don't do local library you see.

**Comment by beatmasterRS** [comment]
In kodi there is no way of coding something like that ;)

**Comment by onlytanmoy** [comment]
Well then, no luck in that case :(
