### ISSUE TITLE
Now playing issue

### ISSUE THREAD

**Issue by PSTrophy** [beatmasterRS/skin.arctic.zephyr.mod#132]
Just thought I'd let you know the now playing info only appears on home menus that have widgets enabled. The preview window is present just not the poster, discart and info.

Might be fixed by your upcoming changes.

**Comment by beatmasterRS** [comment]
What do you mean by "have the widgets enabled"? All main menus have widgets unless you set a background image.

Screenshots would be good as I can't do much with your description. Tell me your exact configuration that leads to the behavior. Then I can try to reproduce it. It always costs me too much time like this.

**Comment by PSTrophy** [comment]
No problem. I have 6 home menus 3 with widgets and 3 with background images set. The now playing works correctly on the widget enabled menus but as soon as I switch to one with a background home menu only the preview window is visible all the movie info disappears. It's not a big deal so don't worry to much :)

**Comment by beatmasterRS** [comment]
I was able to reproduce the problem, thanks :) But I do not know if there is a solution for this. We will see :)

**Comment by PSTrophy** [comment]
No sweat. I thought that might be the case just thought it was worth pointing out :)

**Comment by beatmasterRS** [comment]
Can you please test from this branch https://github.com/beatmasterRS/skin.arctic.zephyr.mod/archive/nowplaying-fix-testing.zip ?

**Comment by PSTrophy** [comment]
The links broken I'll grab GitHub link ;)

**Comment by beatmasterRS** [comment]
Thanks for your feedback! :) With this PR an other issue is fixed as well :)

**Comment by PSTrophy** [comment]
2 for 1 is always nice :)
