### ISSUE TITLE
[Query]Possible to include 'Add to Trakt watch-list'

### ISSUE THREAD

**Issue by onlytanmoy** [beatmasterRS/skin.arctic.zephyr.mod#137]
Hiya, can you include 'Add to Trakt watch-list or custom lists' in this panel? Pls see screenshot, as a + Icon
https://imgur.com/a/LFuQsHL

**Comment by beatmasterRS** [comment]
Unfortunately, I do not use a tract. But do you know a skin where this is implemented? Then I can have a look at it

**Comment by beatmasterRS** [comment]
In the wiki https://github.com/trakt/script.trakt/wiki/Action%3A-addtowatchlist there is an action for that, but 

> This action, will ever only work on library items, consider it an extension of the sync features of the trakt script.

**Comment by onlytanmoy** [comment]
It is implemented in the Aura Mod skin, I am getting a screenshot for you from there in few mins.

**Comment by onlytanmoy** [comment]
Screen record from Aura Mod
https://imgur.com/a/tOLSWd2

**Comment by beatmasterRS** [comment]
Are you using a recent version of the AuraMod, that works with Kodi 19?

**Comment by onlytanmoy** [comment]
At the moment I am using only your skin with Matrix. That screen capture is from Leia. That is ExtendedInfo script which is providing the Trakt add to watch list option.

**Comment by beatmasterRS** [comment]
I've now seen, that tmdbhelper provides trakt management functions: https://github.com/jurialmunkey/plugin.video.themoviedb.helper/wiki/Trakt-Management-Functions

i will try to implement that.

**Comment by onlytanmoy** [comment]
Excellent! Please do, it will be super convenient. Thanks mate.

**Comment by beatmasterRS** [comment]
- This only works for items that have a tmdb_id, or if tmdbhelper provides one. And its not working in embuary.info content. 
- Trakt login data must be added to tmdbhelper
- If this feature is available, an "+" icon is shown in the dialogvideoinfo window (icon will be replaced with better one)

![screenshot00607](https://user-images.githubusercontent.com/3855273/111066120-b11bb300-84bd-11eb-9a47-5fc25477f367.png)

Please test this one:

https://github.com/beatmasterRS/skin.arctic.zephyr.mod/archive/trakt-watchlist-testing.zip

**Comment by beatmasterRS** [comment]
- This only works for items that have a tmdb_id, or if tmdbhelper provides one. And its not working in embuary.info content. 
- Trakt login data must be added to tmdbhelper
- If this feature is available, an "+" icon is shown in the dialogvideoinfo window, left next to the settings button (icon will be replaced with better one)

Please test this one:

https://github.com/beatmasterRS/skin.arctic.zephyr.mod/archive/trakt-watchlist-testing.zip

**Comment by onlytanmoy** [comment]
Wow nice, that was super fast buddy, let me test this one and get back to you.

**Comment by onlytanmoy** [comment]
Ok, I tested it, please see the recording
https://imgur.com/a/cCjCiWm
when I go to a film that actor is part of, the + icon (Add to Trakt watchlist) needs to be there.
In my home screen I am already using widgets linked to my Trakt watchlist, so all those movies are already there in my Trakt, no point in adding them again, so need the + icon/add option for any other movies I navigate to.

**Comment by beatmasterRS** [comment]
As I wrote above, this is unfortunately not possible because embuary.info does not provide tmdb_id.

**Comment by onlytanmoy** [comment]
Oh crap! that's a shame :( nothing much can be done about it I assume, please close this ticket (saying with a heavy heart).

**Comment by onlytanmoy** [comment]
@beatmasterRS on a different note, I do not have all those info showing on the top like your screenshot
https://imgur.com/a/GCBOZs4
what settings I need to enable for that please?

**Comment by beatmasterRS** [comment]
There is no setting to enable this. If the information about the item can be retrieved, then they will be shown. :)

**Comment by onlytanmoy** [comment]
Ah OK, understood 😃 Now that I installed the version you gave me will I still get the update notification for the skin once an update is available?

**Comment by beatmasterRS** [comment]
When you want to get a notification about an update, you musst

 - install my repo-addon. https://github.com/beatmasterRS/repository.matrix.beatmasterRS/blob/main/repository.matrix.beatmasterrs-1.1.zip?raw=true
 - Once you have installed it, you must 
 - install the skin from the beatmasterrs-repo.

Then, when a new version is online, you get a notification or an auto update, if auto update is enabled :)

**Comment by onlytanmoy** [comment]
Thanks mate, I have now installed the skin from BeatMastersRS Matrix repo 👍

**Comment by onlytanmoy** [comment]
@beatmasterRS hi mate, please see this screen record, AZR skin on Matrix
https://imgur.com/a/kotJyoR
will it be possible to implement this context menu thingy at this filmography page?
https://imgur.com/a/gkn46jd
so that way I can add any movie to my Trakt user list.
I did not open a new issue as this is relevant to my original request so updated here :)

**Comment by onlytanmoy** [comment]
@beatmasterRS or is it embuary info content does NOT allow context menu clicking in the movie posters??
