### ISSUE TITLE
KODI19 Sub-menu operation error

### ISSUE THREAD

**Issue by so-o-bima** [beatmasterRS/skin.arctic.zephyr.mod#138]
Thank you.
I'm using the best skin.
I am an Android 19.0 version kodi user.
There is a sub-menu operation error.
The sub menu is displayed in the front of the left screen, not above the menu where the main menu is focused, as shown in the picture.

![Screenshot_20210314-171947](https://user-images.githubusercontent.com/41362720/111062594-28b50680-84ed-11eb-80ef-ff29b0466778.png)

Here's how to reproduce this:
Change the clock in the lower right corner to Disabled.
In the main menu, when the focus moves to the last two menus of the menu, the sub-menu is displayed in front of the left side of the screen.
It needs to be modified so that the sub-menu is displayed in the focused area.
Please check if it can be modified.
Thank you, the developer.
Have a happy every day.

**Comment by beatmasterRS** [comment]
Thanks for your detailed report. Can you please test this branch?

https://github.com/beatmasterRS/skin.arctic.zephyr.mod/archive/homemenu-submenu-fix-testing.zip

**Comment by so-o-bima** [comment]
Thank you for the quick reply and bugfix from the developer.
I just tested the version given by the link.
Now it works.
I think you can add it to the updated version.
I respect the developer.
Thank you.

**Comment by beatmasterRS** [comment]
Thanks for your feedback :)
