### ISSUE TITLE
[Query]Context menu clicking in the movie posters

### ISSUE THREAD

**Issue by onlytanmoy** [beatmasterRS/skin.arctic.zephyr.mod#144]
Hiya, I reckon you missed my comments in the closed issue, therefore created this one :)
Please see this screen record, AZR skin on Matrix
https://imgur.com/a/kotJyoR
will it be possible to implement this context menu thingy at this filmography page?
https://imgur.com/a/gkn46jd
so that way I can add any movie to my Trakt user list.
or is it embuary info content that does NOT allow context menu clicking in the movie posters?

**Comment by beatmasterRS** [comment]
Please take a look at this comment: 

https://github.com/beatmasterRS/skin.arctic.zephyr.mod/issues/137#issuecomment-798896253

I have no control over what items addons add to the context menu, TMDBHelper is imho the only legal compatible matrix addon, that provides trakt management. :)

**Comment by onlytanmoy** [comment]
TMDBHelper & Seren both, so on this screen (https://imgur.com/a/gkn46jd) will it be possible to have context menu show up on long press of remote button? :)
