### ISSUE TITLE
New view 521 - no year or runtime for movies

### ISSUE THREAD

**Issue by meesterexx** [beatmasterRS/skin.arctic.zephyr.mod#151]
The new 521 Big Icons-Flix v2 loses the Year and runtime on movies under the plot as it is on the netflix home screen style . View 510 Big Icons-Flix previously had this info on the side of the plot in the margin. 

This info missing is ok for TV shows using view 521 (they may span multiple years and view 522 episodes has the air date) but may be desired for movies. Can it be added under the plot to match the home screen view? (ratings number is available in the icons on the bottom so not necessary to add back below the plot text)

The screen shots below show netflix home screen and view 521 for the same movie:

![home](https://user-images.githubusercontent.com/13154733/112732263-4d5aa680-8f0f-11eb-9d20-2efed821d7a9.png)

![521](https://user-images.githubusercontent.com/13154733/112732269-521f5a80-8f0f-11eb-871d-bd1cdce22ea4.png)

**Comment by beatmasterRS** [comment]
Unfortunately, I was not yet so satisfied with this view. What do you think of it? I also think it looks much better

![screenshot00705](https://user-images.githubusercontent.com/3855273/112738261-9fc4b300-8f61-11eb-90c2-f950ea342d82.png)

**Comment by beatmasterRS** [comment]
Or with 5 plot lines?

![screenshot00715](https://user-images.githubusercontent.com/3855273/112749576-7a689100-8fc3-11eb-849d-ee89e3507768.png)

**Comment by meesterexx** [comment]
Personally, I like the 5 plot lines ones. 

On a related note, what do you think about the idea of being able to change the color of the movie/show/episode title on all the views/home screens? I've been wondering what it would look like to have the title match (or maybe contrast) the accents/highlights/focusbuttons instead of always being white like the plot/category. Maybe an option could be added to the skin Settings>Colors section?

**Comment by beatmasterRS** [comment]
Sounds good. I'll test that and maybe add an option for it. Thanks a lot!

**Comment by meesterexx** [comment]
Thank you, I really love what you've done with this skin.
