### ISSUE TITLE
Widget request

### ISSUE THREAD

**Issue by sonamibian** [beatmasterRS/skin.arctic.zephyr.mod#155]
Love the skin, thanks for all the frequent improvements!  I would love to have the show title and episode title on two separate lines in the Netflix widget shown below.  The option to replace the show title with the clearlogo would be nice too.  Is that something you could do?

![68029B80-0E66-43C3-8941-537A8CF1F109](https://user-images.githubusercontent.com/44476128/112767505-b78d4d00-8fdc-11eb-9fcf-baacadf438e1.jpeg)

**Comment by beatmasterRS** [comment]
Unfortunately, there is not enough space for this, because the window has a fixed height and the size of the borders is fixed. Therefore, there is only one line for the title. Sorry
