### ISSUE TITLE
HomeMenu Background

### ISSUE THREAD

**Issue by semool** [beatmasterRS/skin.arctic.zephyr.mod#157]
I dont know if its realy a bug but i mean in older Versions this behaviour was not there.
I have set custom Backgrounds for all my MainMenu Entrys (Series/Movies....).
This Background is shown as long as i select a widget Entry, then it will show the Fanart from this Serie/movie/addon.
But when i open the SubMenu of a Main Entry the Background is also switched to the first Entry in the Top Left Corner.

![1](https://user-images.githubusercontent.com/11857931/112875976-3493f180-90c5-11eb-80fc-80c40af15a66.png)
![2](https://user-images.githubusercontent.com/11857931/112875983-378ee200-90c5-11eb-9d4c-424dae7de62f.png)

**Comment by beatmasterRS** [comment]
In which older version was the behavior different? I don't know, because I don't use these backgrounds.

**Comment by beatmasterRS** [comment]
@semool could you test this fix please? :) https://github.com/beatmasterRS/skin.arctic.zephyr.mod/pull/251

**Comment by semool** [comment]
@beatmasterRS yes this fix works fine here :)
