### ISSUE TITLE
[Feature Request]Episode number and title position

### ISSUE THREAD

**Issue by meesterexx** [beatmasterRS/skin.arctic.zephyr.mod#160]
I know layout space in the home view is at a premium, and I have a suggestion to reduce the need for show episode title scrolling.
Would it be possible to have (or the option to enable having) the episode number and title not in the header but as the first line of the plot area (using same font and size as plot) and reduce the actual plot text to 4 lines instead of 5. So essentially you would have:

**SHOW TITLE** (in big font)

SxE - Episode Title 
Plot line 1
Plot line 2
Plot line 3
Plot line 4

Year • Runtime minutes

This would leave the overall space requirements unchanged, reduce scrolling and make the information presented more readily digestible at a glance. It would also maintain essentially the same layout as movies with TITLE/5 plot line text block/1 line for year-runtime-rating.
For a reference point, I am using the Vertical Multi-Widgets Netflix menu/view for home.

Thoughts?

**Comment by beatmasterRS** [comment]
Unfortunately not possible to implement without using a lot of conditions that make the code messy :I

**Comment by meesterexx** [comment]
No worries. Certainly not trying to pile work on your plate, just didn't know how hard/easy it would be to implement.
Thanks for looking into it.  :)
