### ISSUE TITLE
Optimizing view types

### ISSUE THREAD

**Issue by PSTrophy** [beatmasterRS/skin.arctic.zephyr.mod#161]
I was wondering if it's worth looking into optimizing the current view types we have once the open branches are merged. IMO we have too many, 8-10 would be ideal. We currently have 4 of Big Flix a v1 and v2, v1 could be removed plus a few others and have their unneeded code and textures removed along with code optimization on the ones left. Would make things sleeker and it's easier to have less views to focus on. My two cents ;)

It might be a lot of work I'm just hoping you'll consider it. A solid set would be 3 views for movies, 3 for TV shows, 2 seasons views, 2 episodes views and 2 list views. I'm all for choice but what we have is overkill tbh.

Also trying to spell optimization broke my poor British brain, z or s..... I gave up lol

**Comment by beatmasterRS** [comment]
I myself use e.g. only 2-3 views. :D 

With the big code change a few days ago, we have again removed/optimized several 1000 lines of code. This change now makes it easier to make a change in many views. 

There are some users who also use the old home menu views, for example. Now if you really knew that certain views were not being used, i could remove them...

**Comment by PSTrophy** [comment]
I'll have a look at the old views as well and compile a list :)
