### ISSUE TITLE
New watched indictors not showing on season view 516

### ISSUE THREAD

**Issue by meesterexx** [beatmasterRS/skin.arctic.zephyr.mod#164]
Love the new indicators.  The new indicators show on show 521 and episode 522 views, but not on the season 516 view. I would have expected them to replace the checkmarks on the season posters:

![show-new](https://user-images.githubusercontent.com/13154733/113342017-ef0d3980-92fb-11eb-9e99-e33076b75629.png)

![season-old](https://user-images.githubusercontent.com/13154733/113342034-f59bb100-92fb-11eb-8a64-c7cf775d91b6.png)

This is from the latest master downloaded today. Screenshots from TMDBHelper.

**Comment by beatmasterRS** [comment]
Should work now :)

**Comment by meesterexx** [comment]
That did indeed fix it. Thanks! The new indicators are awesome.
