### ISSUE TITLE
Usability issues with BigFlix v2 views

### ISSUE THREAD

**Issue by zeddgb** [beatmasterRS/skin.arctic.zephyr.mod#173]
When we scroll to and select the very last item in our movie library while using the BigFlix v2 view, we can only see the last 2 items in the library, with a whole lot of wasted empty space on the right side of the screen. It looks kind of awkward and makes me lose my place a little when looking for something to watch.

This is how I feel it should work (and roughly how Arctic Zephyr 2 and Horizon currently work):

The currently selected item (movie poster) is always the 3rd item from the left. Scrolling left/right just shifts the posters, until you get near the end, in which case the posters stop shifting and the selected item becomes the 4th from the left, 5th from the left, and so on.

This also affects the BigFlix v2 episode view, which makes using it awkward when you have a small amount of episodes in a season. I hope I have explained this correctly, but if not, I know Arctic Horizon's example is a good one to follow.

Thanks for hearing me out, this skin is excellent.

**Comment by beatmasterRS** [comment]
Thanks for pointing this out. :)

Yes, I don't think that's nice either. You could fix that with "movement". The only "problem" is that when you open the library for the first time, the focus is on position "0" and not on "1". 

Please test https://github.com/beatmasterRS/skin.arctic.zephyr.mod/archive/refs/heads/lists-movement-testing.zip

I'have only changed this in view v2 for movies for now, so we can test

**Comment by zeddgb** [comment]
Thanks for the speedy response beatmasterRS,

I just tested the build you linked, and it works as expected when scrolling to the far right.

I think the right approach would be to have the selected item (i.e. the red outline) be at position 0 initially (but without the poster being cut off as in your screenshot). Then when we scroll to the next item have it at position 1, then position 2, where it will remain until we are near the end of the list. I feel this would work for all the other views as well, including vertical lists.

**Comment by beatmasterRS** [comment]
Please test the updated version here: https://github.com/beatmasterRS/skin.arctic.zephyr.mod/archive/refs/heads/lists-movement-testing.zip

This looks good! Except that the unfocused item disappears immediately when you navigate to the right. This becomes very obvious when you slow down the scroll speed. This behavior also occurs with A:H.

I'll give it some thought :)

**Comment by zeddgb** [comment]
This works great, thanks! I think this behaviour is good enough for all of the views, where applicable.

**Comment by zeddgb** [comment]
Tried the latest changes, works great on the v2 'Episodes' view as well. Any chance you could add this to the 'Shifted' view too?

**Comment by beatmasterRS** [comment]
This will probably take some time, because if it does, it has to be implemented for all views. And just the effect of the sudden disappearance of the no longer focused item does not look good in View 510. We will see...

**Comment by beatmasterRS** [comment]
Btw: the shifted view has a list container, where there is no fixed focus?

**Comment by zeddgb** [comment]
> Btw: the shifted view has a list container, where there is no fixed focus?

Yes, but I feel it is somewhat less user-friendly than this new mode of movement. Some context is always nice when scrolling through a large list of items, and that is exactly what we get with a fixed focus (personally, I think a fixed focus  anywhere between the 3rd position and the center position is perfect).

> And just the effect of the sudden disappearance of the no longer focused item does not look good in View 510

> Except that the unfocused item disappears immediately when you navigate to the right. This becomes very obvious when you slow down the scroll speed

Forgive me, I'm not sure I understand what you mean here. I'm scrolling through, but don't see anything disappearing that shouldn't be disappearing, or anything abnormal. Can you please spell it out for me?

**Comment by beatmasterRS** [comment]
I have slowed down the scrolling time a bit to demonstrate that. Look at half the poster on the left. This looks even worse with View 520/510, because the left poster is completely visible, or the distance of the focused element to the edge is larger.

https://youtu.be/knCry-r_RO0

**Comment by zeddgb** [comment]
Thanks, I see what you mean now. It was hard for my eyes to notice at 50Hz+

**Comment by zeddgb** [comment]
> I have slowed down the scrolling time a bit to demonstrate that. Look at half the poster on the left. This looks even worse with View 520/510, because the left poster is completely visible, or the distance of the focused element to the edge is larger.
> 
> https://youtu.be/knCry-r_RO0
> 
> This behaviour is the same as in Arctic Horizon

I know know why I was not able to see this issue on my system. It only appears for me when wrapping is enabled (I keep it off) AND when there are very few items to scroll through (e.g. a TV show with only 6 episodes).

**Comment by zeddgb** [comment]
Is there any hope of getting this merged? :)

I am still using the lists-movement-testing branch but have noticed that development has been very active over the last month. Unfortunately the branch does not merge onto master cleanly at the moment.

**Comment by beatmasterRS** [comment]
In the last days/months I have been working on other features/problems. But I have not forgotten about the Branch :) I have updated the branch now, so that all new features are included.

**Comment by beatmasterRS** [comment]
With the PR i ve mentioned, the home menu has getting movement. Views will follow i think :)
