### ISSUE TITLE
Clock as part of the bottom OSD

### ISSUE THREAD

**Issue by zeddgb** [beatmasterRS/skin.arctic.zephyr.mod#174]
Any chance we could have an option to make the clock as part of the OSD? I think especially if using the 'Reloaded' OSD it does not have a consistent look with the rest of the UI, and probably takes more space than necessary at the top of the screen.

**Comment by beatmasterRS** [comment]
Do you mean this with "clock"? 

![screenshot00788](https://user-images.githubusercontent.com/3855273/114009044-18c9e180-9863-11eb-9bb0-88e9a9e50a49.png)

![screenshot00787](https://user-images.githubusercontent.com/3855273/114009051-1b2c3b80-9863-11eb-9510-ed994fa80265.png)

**Comment by zeddgb** [comment]
Oh I see, if you disable the "clock" in settings, a different clock shows up in the OSD like in your second screenshot. So the feature is already implemented! :)

For clarity/readability, I would separate the current/finish times. Probably place the current time in the top-right corner of the OSD above the star rating, and change the string for the finish time to something like 'Ends 13:03' or 'Finishes 13:03' (unsure about placement, though could probably keep it where it is). This is of course subjective though though and I don't expect anyone else to share my viewpoint.

**Comment by beatmasterRS** [comment]
Thanks for your comments, I'll think about it :)
