### ISSUE TITLE
Unneeded 'Now Playing...' text in the PVR OSD?

### ISSUE THREAD

**Issue by zeddgb** [beatmasterRS/skin.arctic.zephyr.mod#175]
I'm not sure if this is a bug or whether my EPG is just missing some information, but when I'm watching live TV and I bring up the OSD, the text above the progress bar displays the show that is scheduled to air next. After a few seconds though, that text just changes to 'Now Playing...', then changes back and so on.

Is my EPG missing some data here that should be displayed alongside the 'Now Playing...' text, or should that text just not be there?

**Comment by beatmasterRS** [comment]
This is the same intended behavior as in the OSD when playing movies.  A fade label is used that fades in various information. e.g. the player status: "Now playing".

**Comment by zeddgb** [comment]
Hmm I feel it does not serve any useful purpose for PVR at least. It just continually obscures useful information (the title of the next show) for a moment every few seconds.

**Comment by Rouzax** [comment]
Noticed the samething in movies and TV shows.
Does feel a bit redundant information would rather have a option to persist on of those fading information.
In my case I would like just the genre info to be there.

**Comment by beatmasterRS** [comment]
This behavior is intended, as I like the information in the OSD to be displayed sequentially.
