### ISSUE TITLE
Home Menu transition - Modern Multi-Widgets Netflix

### ISSUE THREAD

**Issue by meesterexx** [beatmasterRS/skin.arctic.zephyr.mod#177]
Is there an option or would it be possible to have an option for the home menu on Modern Multi-Widgets Netflix to behave like the home menu on Vertical Multi-Widgets Netflix? That is, instead of the current sub menu popup box that covers part of the widget, the horizontal main menu slides out of the way (up or down) to reveal the sub menu in it's place similar to the menu transition effect on the Vertical home menu where it slides to the side revealing the sub menu in it's place.

**Comment by beatmasterRS** [comment]
Maybe this is, what you want:

![screenshot00800](https://user-images.githubusercontent.com/3855273/114248928-5af53f00-9999-11eb-96f8-83963f6e9563.png)

Please test this setting:

![screenshot00801](https://user-images.githubusercontent.com/3855273/114248944-6ba5b500-9999-11eb-9e49-f2e17ef2f77e.png)

**Comment by meesterexx** [comment]
That's it exactly, thank you! I missed it the first time around looking in home and furniture and forgot to check extras.
