### ISSUE TITLE
Youtube addon only has 3 views available 

### ISSUE THREAD

**Issue by Juppstein** [beatmasterRS/skin.arctic.zephyr.mod#18]
Due to enforced restrictions by Kodi, addons like YouTube only allow to choose from 3 views; thumbnails, big list, list. To allow more views to be available the skin would need to be changed to allow for this. 

I am aware that there are unofficial addon versions that hack around this, but they are not part of the regularly maintained repositories and thus not updated as frequently or even automatically.

So I'd like to request that the skin is updated so it works in line with the Kodi team recommendations.

Cheers and thanks for the awesome work you've done with this skin so far. It's my go to skin since the very beginning :)

**Comment by beatmasterRS** [comment]
What recommendations from the Kodi team?

Which view do you miss or would you like to have? :)

**Comment by Juppstein** [comment]
Hi, the author of the YT plugin explains it in detail in this FAQ section about half way down the post
https://forum.kodi.tv/showthread.php?tid=267160&pid=2299963#pid2299963

Basically the views which are usually used for movies, TV series or i.e. for the Twitch and Netflix addon are unavailable for the YouTube addon

**Comment by beatmasterRS** [comment]
I've added two more views for video addons like youtube and twitch. Not all views make sense, because many views use posters. It's done in [8604b4f
](https://github.com/beatmasterRS/skin.arctic.zephyr.mod/commit/8604b4f56013524333638c2452bfc4db0e10256f)

**Comment by Juppstein** [comment]
Thanks for adding those views. My question would be why you didn't add views like additional information or similar ones as well. Posters aren't an issue for the YT and Twitch addons since the channel image is used as a general logo and the individual video screens are used similar to episode posters. So in a sense it works like TV series. If I may make a suggestion then it would be nice to allow all views that are related to movies and TV series to also be available to video addons. The the end user can then make his own decisions on which ones he might prefer to use. 

Cheers and have a good day.
