### ISSUE TITLE
Slovak and Czech

### ISSUE THREAD

**Issue by MiCo83** [beatmasterRS/skin.arctic.zephyr.mod#223]
Please add slovak and czech diacritical marks?
Thanks

**Comment by beatmasterRS** [comment]
Could you please explain this in more details? Screenshots might be helpful. Which kodi version?

**Comment by MiCo83** [comment]
where it is to be softened is an empty place.  Example of the Slovak word: Nastavenia vzhľadu. in the translation are missing ľ

Kodi version is 19.0.0![image](https://user-images.githubusercontent.com/74454520/118406864-23f00880-b67e-11eb-892f-f3bb9c25dfce.jpeg)

**Comment by beatmasterRS** [comment]
Please switch to an arial based font type, e.g. Arial or Arial 2 in "settings" -> "skin" -> "fonts"

**Comment by MiCo83** [comment]
Thank you very much, it helped
