### ISSUE TITLE
Slow loading TMDB

### ISSUE THREAD

**Issue by najibrajak** [beatmasterRS/skin.arctic.zephyr.mod#230]
I have issue with TMDB which is too slow to load. It takes ages to finish loading (including search, widgets, . And its not happen on arctic zephyr 2. Pls advise.

**Comment by beatmasterRS** [comment]
Please provide a debug log with a description, what you have done, so i can see step by step, whats going on.

**Comment by najibrajak** [comment]
It seems okay now.. not sure how.. i think i'm gonna close thsi issue
