### ISSUE TITLE
Thumbnail icons not appearing in thumbnail view

### ISSUE THREAD

**Issue by ohmichael** [beatmasterRS/skin.arctic.zephyr.mod#232]
I’m using leia and switched the gui version in your matrix version to match leias - the skin works on leia only thing I notice is the icons in thumbnail view do not load but they do in list view. They work in thumbnail view on the old leia version. Thank you for your hard work.

**Comment by ohmichael** [comment]
One last thing the addons won’t show version updates to let me install an addon this is my first time using your new skin sorry for the trouble.

**Comment by beatmasterRS** [comment]
For using leia please download the leia version from the leia branch:

https://github.com/beatmasterRS/skin.arctic.zephyr.mod/archive/leia.zip

You can also install the leia repository in Kodi and get the skin from there: 

https://github.com/beatmasterRS/repository.beatmasterRS/blob/master/repository.beatmasterrs-1.0.zip?raw=true

The bevaiour for thumbs in leia is not the same as in matrix.
