### ISSUE TITLE
System info widget is not appearing on leia mod

### ISSUE THREAD

**Issue by ohmichael** [beatmasterRS/skin.arctic.zephyr.mod#233]
When I place System Info on settings as widget it doesn’t appear or it appears to not be showing this is why I tried your matrix mod reloaded on leia which didn’t turn out as expected - if you could have some of those features from reloaded with the System Info widget fixed it would be awesome :)) Thank You so much! Here is a screenshot of what System Info widget looks like when used.
![image](https://user-images.githubusercontent.com/17955639/119173334-bf8dca00-ba2c-11eb-96a9-1dbd1eaa8149.jpg)

**Comment by ohmichael** [comment]
Modern multi-widgets sorry for the trouble it’s been bothering me

**Comment by ohmichael** [comment]
It does it in vertical multi-widgets also
![image](https://user-images.githubusercontent.com/17955639/119181537-59f30b00-ba37-11eb-88df-7e77f10eaa22.jpg)

**Comment by beatmasterRS** [comment]
Please provide the script-skinshortcuts-includes.xml file, localed in addons\skin.arctic.zephyr.mod\1080i folder

**Comment by ohmichael** [comment]
it wouldn't let me attach the file for some reason xml or something is not allowed but I uploaded it to my host [http://ohmichael.mycopy.xyz/skin/script-skinshortcuts-includes.xml](url)

**Comment by beatmasterRS** [comment]
Unfortunately, I can not see why the widget is not displayed, nor can I reproduce the problem. Content  and the widget layout are set fine.

The only tip I can give you is to reset the widget configuration in Skin settings -> Customize homemenu ->restore menu items -> Reset to skin defaults

**Comment by ohmichael** [comment]
It works in classic view

**Comment by ohmichael** [comment]
Here’s what I also noticed beatmasterRS when I add system info widget to another menu item like weather it shows in modern & vertical multi-widgets - some reason the category setting has system info widget hidden for me - I deleted settings from menu and added it again custom but it does it still - hope that helps.

**Comment by beatmasterRS** [comment]
Thanks for your further information. I have now tried several times to reproduce this, but unfortunately I have not been able to do so...

I know that SkinShortcuts can hide main menu items (e.g. movies if there are no movies in the library), but if it can do the same for widgets I don't know

**Comment by ohmichael** [comment]
I use kodi 18.9 if it makes a difference.

**Comment by beatmasterRS** [comment]
I have a 18.9 Installation as well, but it doesn't make a difference, I still can't reproduce that.

**Comment by ohmichael** [comment]
Alright ty for all the help I’ll close this now you’ve been more then patient.

**Comment by ohmichael** [comment]
If by some chance this becomes open again can you close it please - letting you know I fixed it - it seems for some reason when you have 11 or more menu items the only widget that show for the last 2 menu items is the submenu widget like for power and settings cuz I stick them at the end but if you stick menu items you don’t use at the end of the menu and put settings before the last two useless menu items then Settings Info widget appears - just letting you know for future endeavors on this skin.
