### ISSUE TITLE
OSD plot information scrolls when it does not need to

### ISSUE THREAD

**Issue by zeddgb** [beatmasterRS/skin.arctic.zephyr.mod#236]
When the plot information consists of just two lines, the entire plot text is already visible when the OSD is activated. But after a few seconds the plot information is (pointlessly) scrolled so that only the second line is now visible.

**Comment by zeddgb** [comment]
I have also noticed that it is possible for the OSD to be mid-scroll or end-of-scroll when you activate it. This means that sometimes I am waiting ~10-20 seconds after activating the OSD so that I can read the plot from the beginning.

The OSD should always be showing the beginning of the plot text whenever it is activated.

**Comment by beatmasterRS** [comment]
Unfortunately, I can't reproduce this yet. Which OSD are you using? Which font? Screenshots would be helpful

**Comment by zeddgb** [comment]
This is with the Standard OSD, and "AZ Standard" font.

Good idea to ask about the font, I just tried using the skin's default font and it (correctly) does not scroll when there are only 2 lines of plot.

I think issue No. 2 (being able to activate the OSD and have the text displayed mid-scroll) would affect either font though if the plot text is long enough to warrant scrolling.

**Comment by beatmasterRS** [comment]
Please test the latest master. I made a change that should cause the plot to start scrolling after 10 seconds after the plot is displayed:

https://github.com/beatmasterRS/skin.arctic.zephyr.mod/commit/9c74deb1326644c44fc7894a2dbe62ec51cd0b48 [commit]

**Comment by zeddgb** [comment]
That works great, thanks. It is still possible to catch the plot text mid-scroll if you dismiss and re-activate during a scroll, but I don't feel that's a huge problem.

The unnecessary scrolling with the AZ Standard font still persists.

**Comment by beatmasterRS** [comment]
> That works great, thanks. It is still possible to catch the plot text mid-scroll if you dismiss and re-activate during a scroll, but I don't feel that's a huge problem.

Is there a skin where this works as you want it to?

> The unnecessary scrolling with the AZ Standard font still persists.

Not possible to fix, cause the AZ standard font has a different linespacing then the default font.

**Comment by beatmasterRS** [comment]
EDIT: cuttently doing some tests with AZ standard
