### ISSUE TITLE
TV Show ratings icon - all show as R rated

### ISSUE THREAD

**Issue by meesterexx** [beatmasterRS/skin.arctic.zephyr.mod#258]
Downloaded latest master just now, I noticed all TV shows are showing as R. 
This is from TMDBHelper.
![screenshot00000](https://user-images.githubusercontent.com/13154733/120347864-a4dc1080-c2ca-11eb-8ecf-3c421c2f3c24.png)

![screenshot00001](https://user-images.githubusercontent.com/13154733/120347883-a9a0c480-c2ca-11eb-82e1-c9b940c89b2f.png)

**Comment by meesterexx** [comment]
FYI, movie ratings are fine.

**Comment by beatmasterRS** [comment]
With an older version of the skin all is fine? Please enable debug logging and extended debugging infos in skin settings and provide screenshots like you have done, thanks :)

**Comment by meesterexx** [comment]
I checked skin vers 1.1.39 - 1.1.4.1 and the issue is there. I guess I didn't notice before. It was probably the new colorful icon that caught my attention  :)

Digging deeper, it seems it's specific to TMDBHelper in some way as 2 "other" addons didn't have the issue. Looking at the screenshot for TMDBHelper it shows the correct rating TV-Y7, but it maps to mpaa/r.png. In the other 2 screenshots, you can see it  maps correctly to TV-Y7.png.

FYI, I did clear the TMDBHelper databases in userdata\addon_data\plugin.video.themoviedb.helper\database before taking screenshots, though the debug info does show it reporting the correct rating, only the png mapping is wrong.

TMDBHelper - r.png:
![screenshot00000](https://user-images.githubusercontent.com/13154733/120351488-ee7a2a80-c2cd-11eb-97a2-e78a0639cd4e.png)

Non-Official addon 1:
![screenshot00001](https://user-images.githubusercontent.com/13154733/120351558-fafe8300-c2cd-11eb-8fb5-ee72429ab395.png)

Non-Official addon 2:
![screenshot00002](https://user-images.githubusercontent.com/13154733/120351607-05208180-c2ce-11eb-8370-95be147995bc.png)

**Comment by beatmasterRS** [comment]
Please be sure, that in tmdbhelper the setting for "mpaa rating prefix" doesn't contain spaces.

**Comment by meesterexx** [comment]
That was it! There was a space after the word Rated. I corrected it:
"<setting id="mpaa_prefix">Rated</setting>"
 and after clearing Kodi cache, tmdbhelper dbs, and restarting kodi it worked. Wonder if the space was in there by default because I never consciously set it.  ¯\_(ツ)_/¯

Sorry for the false positive and thank you! Please close this one :)

**Comment by beatmasterRS** [comment]
No problem :)
