### ISSUE TITLE
2.00:1 video being reported as 1.85:1

### ISSUE THREAD

**Issue by richardsim7** [beatmasterRS/skin.arctic.zephyr.mod#289]
![image](https://user-images.githubusercontent.com/35804777/121758187-532c5500-cb18-11eb-97fb-f361a4ceca2c.png)

![image](https://user-images.githubusercontent.com/35804777/121758207-64756180-cb18-11eb-9011-35424522dbbc.png)

**Comment by beatmasterRS** [comment]
Does this also happen with other skins?

**Comment by richardsim7** [comment]
Yes, it appears to happen with the default skin also

I'm guessing that means Kodi itself doesn't have a media flag for 2.00:1 content?

![image](https://user-images.githubusercontent.com/35804777/122227846-2dec6d80-ceaf-11eb-8d5e-e25271c70eb6.png)

**Comment by beatmasterRS** [comment]
I have no Idea, sorry.

**Comment by beatmasterRS** [comment]
I close this issue, so if there are any news on this, feel free, to reopen, thanks.
