### ISSUE TITLE
Issue files.

### ISSUE THREAD

**Issue by IanWONeill** [beatmasterRS/skin.arctic.zephyr.mod#3]
![ba rd scanna n na ha ireann](https://user-images.githubusercontent.com/20154372/51729964-b0b9c700-206d-11e9-9798-0b2d00e7e293.png)

The file '_bÃ³rd scannÃ¡n na hÃireann.png_' causes issues while zipping (may not show up using WinRAR etc but using a standard "Send-to: Compressed Zip File" with Windows will trip the error.

The only reason I found this error was because while porting the build over to XBOX ONE I noticed a lot of Folders and Files missing completely, this is because the method I had used to compress the files to a '.zip' (WinRAR) skated over the issue without prompt - Not adding in a lot of the files after this specific one in order.

You will need to remove/rename this file to stop errors in future for other users. (:

**Comment by IanWONeill** [comment]
https://i.imgur.com/422Mz19.png

**Comment by IanWONeill** [comment]
also found these : 
'conspiraÃ§Ã£o filmes.png'
'conspiraÃ§ao filmes.png'
'conspiraÇõao filmes.png'
'conspiraÇõÇœo filmes.png'
'global asylumâ the.png'
'pÇœo com ovo filmes.png'
'radio telefÃ­s Ãireann.png'
'rtÃ.png'
'zespÃ³Å filmowy oko.png'
'zespÃ³Å filmowy tor.png'
'zespÃ³l filmowy oko.png'
'zespÃ³l filmowy tor.png'
'zespÇül filmowy oko.png'
'zespÇül filmowy tor.png'

also possible some Pathe ones but I will let you know.

**Comment by beatmasterRS** [comment]
Thank you, i will look at this soon.

**Comment by IanWONeill** [comment]
I didn't manage to figure out exactly which files were breaking the extraction process on the XBOX ONE because I wasn't in Developer mode and would have had to have pushed over the build over and over while uploading the logs which would be a pain - but removing the folders completely for the Studio, etc. Solved my issues - This is a quick fix for a single person build but if it were to go viral I think this would need to be fixed as this is by far the nicest Theme for Kodi on XBOX ONE.

**Comment by beatmasterRS** [comment]
Studiologos folder will be removed, cause AZ is not using icons from this folder. Thanks for your support.

**Comment by beatmasterRS** [comment]
https://github.com/beatmasterRS/skin.arctic.zephyr.mod/commit/8670669c473f827d906d434a49914b916c6a03eb
