### ISSUE TITLE
No station logos in PVR views

### ISSUE THREAD

**Issue by b-jesch** [beatmasterRS/skin.arctic.zephyr.mod#30]
There are no station logos shown in some/all PVR windows (EPG view, channel views) in Kodi 19. Same setting in K18 works, logos are shown.

**Comment by beatmasterRS** [comment]
Can you provide a screenshot of this issue? The PVR Icon processing/handling in kodi 19 hasn't changed, so there is still the $INFO[Listitem.Icon] infolabel for that.

**Comment by b-jesch** [comment]
Of course:

Kodi 19:

![Bildschirmfoto von 2020-12-26 14-56-44 png](https://user-images.githubusercontent.com/10152384/103152937-084a9b00-478d-11eb-840a-d99f1dd29f34.jpg)
![Bildschirmfoto von 2020-12-26 14-57-16 png](https://user-images.githubusercontent.com/10152384/103152938-097bc800-478d-11eb-9b4f-f443ed807609.jpg)
![Bildschirmfoto von 2020-12-26 14-58-21 png](https://user-images.githubusercontent.com/10152384/103152939-0a145e80-478d-11eb-899c-94daf96218dd.jpg)

Kodi 18, another client, same access data to a Tvheadend Server and identical settings in PVR HTS client as above:

![screenshot007 png](https://user-images.githubusercontent.com/10152384/103152972-37610c80-478d-11eb-8fea-86ca2480d5f0.jpg)
![screenshot008 png](https://user-images.githubusercontent.com/10152384/103152986-37f9a300-478d-11eb-9aaa-9d8e84940430.jpg)

**Comment by beatmasterRS** [comment]
That's strange. Does this also happen on other skins like estuary?

**Comment by beatmasterRS** [comment]
I have now tested this again with a fresh installation (libreelec, kodi 19 beta, odroid n2) and still can not reproduce this behaviour. All channel-icons are displayed correctly in all views/epg. My m3u with channel icons is the following: 

https://raw.githubusercontent.com/jnk22/kodinerds-iptv/master/iptv/kodi/kodi_tv_main.m3u

**Comment by b-jesch** [comment]
Maybe a problem with the TVHeadend PVR client. With the simple IPTV client the station logos are visible.

**Comment by b-jesch** [comment]
This is indeed an issue with the TVH client. Requesting the image via browser is successfull. I have to elaborate this and close the issue.

`2020-12-28 20:04:29.227 T:3174    ERROR <general>: CCurlFile::Open failed with code 401 for http://192.168.10.11:9981/imagecache/183874:
                                                   
2020-12-28 20:04:29.227 T:3174    ERROR <general>: Open - failed to open source <http://USERNAME:PASSWORD@192.168.10.11:9981/imagecache/183874>
2020-12-28 20:04:29.228 T:3176    ERROR <general>: CCurlFile::Stat - Failed: HTTP response code said error(22) for http://USERNAME:PASSWORD@192.168.10.11:9981/imagecache/183877
2020-12-28 20:04:29.228 T:3176    DEBUG <general>: GetImageHash - unable to stat url http://USERNAME:PASSWORD@192.168.10.11:9981/imagecache/183877`
