### ISSUE TITLE
AZR english Strings.po not used in some case

### ISSUE THREAD

**Issue by Nanomani** [beatmasterRS/skin.arctic.zephyr.mod#300]
see explain here : 

https://forum.kodi.tv/showthread.php?tid=337862&pid=3043184#pid3043184

**Comment by beatmasterRS** [comment]
Does this only occur, when the language file doesnt has the located strings? It's strange, that when i add the missing strings to e.g. "Eperanto", so the file conatins the same strings as "English", but the issue still exsists...

**Comment by beatmasterRS** [comment]
Could you please test? :)

https://github.com/beatmasterRS/skin.arctic.zephyr.mod/archive/refs/heads/language-strings-fix-testing.zip

**Comment by Nanomani** [comment]
It is ok for me. :)
Not tested all changed id  strings...
If you are use only empty strings id from Kodi all will be fixed

**Comment by beatmasterRS** [comment]
I have first changed all from 38000 upwards. Used now from 38500

Thanks a lot :)

**Comment by beatmasterRS** [comment]
Maybe we should use folder named like resource.language.en_gb to get rid of this issue and use all strings?

**Comment by beatmasterRS** [comment]
https://kodi.wiki/view/Language_support#Layout_of_the_language_folders

**Comment by beatmasterRS** [comment]
I have not tested yet, but maybe the issues got fully fixed..

**Comment by Nanomani** [comment]
more important : 
- strings 31000 thru 31999 reserved for skins
- translation is empty for "en_GB" labels

**Comment by beatmasterRS** [comment]
I've made a new branch for that:

https://github.com/beatmasterRS/skin.arctic.zephyr.mod/tree/language-strings-testing

Should i close this issue and do a PR with the new branch or what do you mean is easier to discuss and to test?

**Comment by beatmasterRS** [comment]
strings.po file with only a few kb, i have deleted for now

**Comment by Nanomani** [comment]
Very good decision 👍 

for this "chain 31000 to 31999 reserved for skins", the work is huge ...

msgctxt "#31xxx" => 188 strings 
msgctxt "#37xxx" => 483 strings :/
msgctxt "#38xxx" => 19 strings :/

moreover I am sure that there are values that are not or no longer used ...

**Comment by beatmasterRS** [comment]
Omg I thought that the most strings are in the correct range :( I will start to fix this issue today, for a long time :D :l

**Comment by beatmasterRS** [comment]
Do you know an easy way to to this? :l

**Comment by Nanomani** [comment]
Perhaps :) 
I have already extracted all the "strings ID" that must be replaced :) 
I test 2 batch for : 

1. find all "strings ID" not use
2. replace in all code "strings ID" that must be replaced

give me some time :)

**Comment by beatmasterRS** [comment]
Have you any news on this? Can you use a finde/replace list in TextCrwaler?

**Comment by beatmasterRS** [comment]
If you have the id's, that must be changed, i could generate a list in this format with php:

![Image1](https://user-images.githubusercontent.com/3855273/122675705-f34e4200-d1da-11eb-8aff-31b2dd624082.jpg)

**Comment by Nanomani** [comment]
First I thinks we must eliminate all ID strings useless ?

"find all "strings ID" not use" => 153 strings :D

msgctxt "#31xxx" => 68 strings
msgctxt "#37xxx" => 85 strings

Result : 

[list_strings_ID_not_found.txt]

[results.txt](https://github.com/beatmasterRS/skin.arctic.zephyr.mod/files/6682437/results.txt)

My batch : (for run del .txt)

[search_strings_ID_not found.cmd.txt](https://github.com/beatmasterRS/skin.arctic.zephyr.mod/files/6682434/search_strings_ID_not.found.cmd.txt)

**Comment by beatmasterRS** [comment]
Omg, this looks difficult for me :D If i can do anything to help you, please let me know :)

**Comment by Nanomani** [comment]
I search a solution for :  

search strings then if find delete the line + 2 next line for strings.po :)

**Comment by Nanomani** [comment]
153 "strings ID" cleaning for strings.po DE, EN, FR

I have post a PR for testing
https://github.com/beatmasterRS/skin.arctic.zephyr.mod/pull/316

can you try and tell me if i can continue with other strings.po or if there is a problem

**Comment by beatmasterRS** [comment]
Yes, it works absolutely fine for me :) Please continue :) If you like, please add all follwing commits to the PR you have opened :)

**Comment by beatmasterRS** [comment]
Thank you so much! :)

**Comment by Nanomani** [comment]
your welcome :)
Thank you for your trust and for this remarkable skin :)

**Comment by beatmasterRS** [comment]
Maybe we can get this skin to the official kodi repo :)

**Comment by Nanomani** [comment]
> Maybe we can get this skin to the official kodi repo :)

It's funny i was thinking the same thing. Yes this will be cool and deserved

**Comment by Nanomani** [comment]
Small detail, what do you think for the next update 1.2.0 :D
