### ISSUE TITLE
Disrupted audio when EPG Guide is open and video/TV plays in background

### ISSUE THREAD

**Issue by b-jesch** [beatmasterRS/skin.arctic.zephyr.mod#31]
If the EPG window is displayed for a longer time (> 10 secs) and the TV program (or video) is running in the background, this leads to an interrupted audio every few seconds. Concerns both K18 and K19.

**Comment by beatmasterRS** [comment]
This is imho not skin related, cause this behaviour is also present in other skins, that are not showing the current playing video in the background.

**Comment by b-jesch** [comment]
So say that is window related depending of the anatomy of the EPG window.  This behaviour does not appear in Estuary or Estuary Mod V2 (Kodi 19). To avoid interuption both skins shows the actual video: Estuary in background, ModV2 within a small preview window.

Maybe you could change the static window in the EPG timeline against the video preview?

**Comment by beatmasterRS** [comment]
Please test the latest version. I've added a hidden video window, to prevent audio errors. 

https://github.com/beatmasterRS/skin.arctic.zephyr.mod/commit/c7acce66c374958df1400fafcb8a7c7785ef960a

**Comment by b-jesch** [comment]
Audio disruption is indeed gone with the new version. Thank You.

**Comment by b-jesch** [comment]
This issue is back on 1.1.22 and the new 1.1.23.

**Comment by beatmasterRS** [comment]
I changed this, because it results in a super slow playback in the main menu on my odroid n2, even if i had a now playing windowed videowindow enabled. With the skin amber on my n2, there is the same behaviour for me, when i have "now playing" enabled and a windowed videowindow is visible on the homemenu. So i decided to add this only as an option.

![screenshot00481](https://user-images.githubusercontent.com/3855273/109709064-6be1b200-7b9c-11eb-8a19-e15034e9da9f.png)

With this option enabled, on windows 10 everything is fine, no errors. With this option enabled on my odroid N2, the homemenu navigation is superslow.

Absolutely strange...

**Comment by b-jesch** [comment]
Ah ok, I didn't saw this setting in the setup menu. Everything is fine now. The hidden window is indeed very small, only 2x1 Pixels. Maybe the odroid cannot resize the video content properly to this small window so you have to enlarge to e.g. 300x200 Pixel?

**Comment by beatmasterRS** [comment]
Do you mean the matrix version? In the first version the video window was limited to 1x2 px, but this caused errors, so I changed the video window size to fullscreen:

https://github.com/beatmasterRS/skin.arctic.zephyr.mod/blob/890016d332f7f8992d263a4fbb3475dcb0597745/1080i/Includes.xml#L483-L488

https://github.com/beatmasterRS/skin.arctic.zephyr.mod/blob/890016d332f7f8992d263a4fbb3475dcb0597745/1080i/Includes.xml#L498

**Comment by b-jesch** [comment]
Yes, I meant the commit  c7acce6 some posts above here. If the hidden window is now in fullscreen I have no clue. Is the time lag reported in the debug log?

**Comment by beatmasterRS** [comment]
https://paste.kodi.tv/avuzotades.kodi

As you can see, there are a few audio-errors, I think it starts at 2021-03-02 22:08:13.310 T:26016

But i am not familiar with the kodi core functions, to be more specific.

In "Aeon MQ 8 - matrix mod" there is the same behaviour, if you are in skin-settings window. In homemenu, where the videowindow is visible, everythink is fine.

**Comment by b-jesch** [comment]
`2021-03-02 22:08:17.528 T:3920  WARNING <general>: CVideoPlayerVideo::OutputPicture - timeout waiting for buffer`

These are the messages if no video window is present. There are dozens of them - between the embuary helper messages (which has nothing to do with the buffer errors).

Is the log above from the odroid?

**Comment by beatmasterRS** [comment]
No, from windows 10

**Comment by beatmasterRS** [comment]
Could you please test this in estuary mod? If the play video in background option is enabled, there are a lot of audio errors every 7-10 seconds for me.

![screenshot00617](https://user-images.githubusercontent.com/3855273/111204654-a8fb6a80-85c6-11eb-9576-508c52adb2b8.png)

**Comment by b-jesch** [comment]
The problem is reversed ;) . If "show video on background" is disabled (like the screenshot) and a video is playing, there are audio errors. It seems this is a general problem with video without display window on Kodi.

**Comment by beatmasterRS** [comment]
Thanks for your feedback. Then i'll close this issue, till there is something new.
