### ISSUE TITLE
Bug or expected? - No background on weather widget focus

### ISSUE THREAD

**Issue by meesterexx** [beatmasterRS/skin.arctic.zephyr.mod#310]
I am not using any weather art, but I have a background image defined for the home menu entry and a fallback image for the skin defined. I am using the weather widget and when unfocused or when entering weather from the widget, I see my background. When I arrow up to focus on the widget, the background disappears (see pics below). Is this a bug or is this expected as I'm not using any weather art?

Unfocused:
![screenshot00000](https://user-images.githubusercontent.com/13154733/122421415-58dfcb80-cf5a-11eb-8ed5-de8505637c21.png)

Focused:
![screenshot00003](https://user-images.githubusercontent.com/13154733/122422027-d0155f80-cf5a-11eb-93a7-ccb1b8f74b3a.png)

Entered weather from widget:
![screenshot00002](https://user-images.githubusercontent.com/13154733/122422119-e6bbb680-cf5a-11eb-85a1-83a051e2bc5d.png)

**Comment by Nanomani** [comment]
I can reproduce that with modern multi and vertical multi layout
I don't think this is what expected. :)

**Comment by beatmasterRS** [comment]
@meesterexx @Nanomani 

I was also able to reproduce this issue. Could you please test this version here:

https://github.com/beatmasterRS/skin.arctic.zephyr.mod/archive/refs/heads/weather-widget-background-patch-1.zip

?

**Comment by Nanomani** [comment]
this works fine now :)
thanks

**Comment by meesterexx** [comment]
Yes, fixed for me in 1.1.47. Thank you!
