### ISSUE TITLE
[code] cleaning all space end line + convert indentation to TAB 

### ISSUE THREAD

**Issue by Nanomani** [beatmasterRS/skin.arctic.zephyr.mod#328]
With the advise of @fabricionaweb clean all "space" useless is very easy (magic)
see the discussion here : https://github.com/beatmasterRS/skin.arctic.zephyr.mod/pull/327

I would like to replace all the indentation "space" by indentation "tab". I have found a great tools for that.
https://www.sublimetext.com/docs/indentation.html

So there is no risk to delete / replace "spaces" use in `<label>` 

@beatmasterRS if you are agree I post a PR for all of that :D 
if not please fell free to close this :)

thanks for reading.

**Comment by beatmasterRS** [comment]
No extra tools needed ^^ Just do a find and replace for the regular expression 

>>[ \t]+$

**Comment by beatmasterRS** [comment]
You can always do a PR :)

**Comment by Nanomani** [comment]
> No extra tools needed ^^ Just do a find and replace for the regular expression
> 
> > > [ \t]+$

But this that the "space" will be replace everywhere :/ no ?

![1](https://user-images.githubusercontent.com/3939543/123399315-c3b98400-d5a4-11eb-9a83-81e9df7fc987.jpg)

**Comment by beatmasterRS** [comment]
Just have a look at my PR :)

**Comment by Nanomani** [comment]
all seems very good :)

1 - clean all "space"=> **done**
2- indentation "space" by indentation "tab" => _**not done**_ :)

**Comment by beatmasterRS** [comment]
With 2. you mean replace "	" by "    "?

**Comment by Nanomani** [comment]
> With 2. you mean replace "tab" with "4 spaces"?

the reverse replace "4 spaces" by "tab" :D 

I know there are 2 schools : 

1. 4 spaces
2. 1 Tab (IMHO better but it is very personal, practice used by team kodi for Estuary)

**Comment by beatmasterRS** [comment]
I had changed this to 4 spaces a long time ago (when I noticed I was using TAB and the skin was using 4 spaces), because jurialmunkey does this in his skins too. :)

**Comment by Nanomani** [comment]
> I had changed this to 4 spaces a long time ago (when I noticed I was using TAB and the skin was using 4 spaces), because jurialmunkey does this in his skins too. :)

I understand. I don't want change the world :D
We stay like that and I replace all "tab" with "4 spaces" 
Perhaps you are already do that in your PR ?

**Comment by beatmasterRS** [comment]
Should be done :)

**Comment by Nanomani** [comment]
after a quick search there only Includes_Images.xml with "tab"
