### ISSUE TITLE
Thumbs or background is not show with podcasts add-ons

### ISSUE THREAD

**Issue by Nanomani** [beatmasterRS/skin.arctic.zephyr.mod#361]
If you use podcasts add-ons (RSS Podcasts /  Apple Itunes Podcasts) in widgets, thumb is show very fine.
The background set in "skin-settings => home menu" too :) 

eg : 
![2](https://user-images.githubusercontent.com/3939543/124388602-dee26d00-dce3-11eb-9b5b-5f610c023c87.jpg)

then when you listen one of this podcast : 
- the thumb is not show in full screen and in home ("NowPlaying" enable)
- the background is not show too

eg : 

fullscreen 
![1](https://user-images.githubusercontent.com/3939543/124388774-9d05f680-dce4-11eb-8bdb-ddff6a46dba0.jpg)

home 
![3](https://user-images.githubusercontent.com/3939543/124388779-a3946e00-dce4-11eb-8f93-fb4330c3566a.jpg)

:D

**Comment by beatmasterRS** [comment]
Where should the background-image come from? From ArtistSlideshow?

**Comment by Nanomani** [comment]
> Where should the background-image come from? From ArtistSlideshow?

not at all :)

![1](https://user-images.githubusercontent.com/3939543/124390333-61baf600-dceb-11eb-8dd4-f1ebbdcc22c9.jpg)

**Comment by beatmasterRS** [comment]
Could you please try to remove line 386 and test?

https://github.com/beatmasterRS/skin.arctic.zephyr.mod/blob/5bad81859dc3bd3eed5df5ae791362101309d362/1080i/Includes.xml#L386

**Comment by beatmasterRS** [comment]
in music visualisation settings you have also set a fallback image?

![screenshot00135](https://user-images.githubusercontent.com/3855273/124390687-02f67c00-dced-11eb-984c-4200de87f355.png)

**Comment by Nanomani** [comment]
> Could you please try to remove line 386 and test?
> 
> https://github.com/beatmasterRS/skin.arctic.zephyr.mod/blob/5bad81859dc3bd3eed5df5ae791362101309d362/1080i/Includes.xml#L386
> 
> EDIT: for homemenu

This make the job. the issue with background is gone :) 
thanks

**Comment by Nanomani** [comment]
> in music visualisation settings you have also set a fallback image?
> 
> ![screenshot00135](https://user-images.githubusercontent.com/3855273/124390687-02f67c00-dced-11eb-984c-4200de87f355.png)

yes thanks :)  
I listen only podcasts audio (no video)

**Comment by beatmasterRS** [comment]
I don't know at the moment how to fix this so that it works in all situations :D 

With removing line 386, when no AS image was found:

![screenshot00136](https://user-images.githubusercontent.com/3855273/124391127-5ff33180-dcef-11eb-828a-b0211d64ea6c.png)

When AS image was found:

![screenshot00139](https://user-images.githubusercontent.com/3855273/124391143-700b1100-dcef-11eb-8912-640a70d40c8a.png)

Line 386 enabled, results in the following, when no AS image was found:

![screenshot00141](https://user-images.githubusercontent.com/3855273/124391215-d7c15c00-dcef-11eb-90c9-a16cef6c4664.png)

I hate the background varianle :D

**Comment by beatmasterRS** [comment]
We will see, who has first a solution for that, that fits all needs :D

**Comment by Nanomani** [comment]
If you have an intuition for the thumbnail displayed in the widgets but not on the cover I take. Even the beginnings of an idea. You always have good advice. thanks :)

**Comment by Nanomani** [comment]
> I hate the background varianle :D

I know :D

**Comment by Nanomani** [comment]
> If you have an intuition for the thumbnail displayed in the widgets but not on the cover I take. Even the beginnings of an idea. You always have good advice. thanks :)

perhaps an new condition in "Includes_Images.xml" line 203

```
    <variable name="PlayerPoster">
        <value condition="!String.IsEmpty(Player.Art(tvshow.poster))">$INFO[Player.Art(tvshow.poster)]</value>
        <value condition="!String.IsEmpty(Player.Art(poster))">$INFO[Player.Art(poster)]</value>
        <value>$INFO[Player.Art(thumb)]</value>
    </variable>
```

**Comment by Nanomani** [comment]
> We will see, who has first a solution for that, that fits all needs :D

sorry I don't kwon how to add code like you from source file in github ...

can you replace line 386 with that : 

        `<value condition="Skin.HasSetting(extended.nowplaying) + Window.IsVisible(home) + !ControlGroup(301).HasFocus() + !Skin.HasSetting(home.dontshowfanart) + String.IsEmpty(Container(301).ListItem.Property(backgroundPlaylist)) + String.IsEmpty(Player.Art(fanart)) + String.IsEmpty(Window(Visualisation).Property(ArtistSlideshow.Image)) + Player.HasMedia + String.IsEmpty(Container(300).ListItem.Property(background)">common/null.png</value>`

make a test please :)

**Comment by beatmasterRS** [comment]
Works for me, you ar a champ :D

**Comment by beatmasterRS** [comment]
commit is done: ad2bc2e547c26dbbdbaa1059c15c5f51770c764b :)

**Comment by beatmasterRS** [comment]
>>sorry I don't kwon how to add code like you from source file in github ...

I dont know, if you mean this?

![Image1](https://user-images.githubusercontent.com/3855273/124394917-cbde9580-dd01-11eb-90eb-31f0be3299f3.jpg)

Choose "Copy permalink", paste the link here and the code line s will be shown. You can also choose more than one line.

**Comment by Nanomani** [comment]
> I dont know, if you mean this?

yes. thanks :)
