### ISSUE TITLE
[Bug] the previous fanart is displayed in addition to the default fanart with stream radio

### ISSUE THREAD

**Issue by Nanomani** [beatmasterRS/skin.arctic.zephyr.mod#362]
the previous fanart is displayed in addition to the default fanart with stream radio : 

reproduce : 
- enable artist.slideshow
- set fallback background for OSD music 
- play music (see last fanart displayed)
- play stream radio (eg : with plugin.audio.radio_de )

expected : 
- only display fallback background not the last artist fanart with last music playing

![screenshot00014](https://user-images.githubusercontent.com/3939543/124396701-6db6b000-dd0b-11eb-831a-08b76f529997.png)

don't worry it is for myseft :D 
but all help are welcome :)

**Comment by Nanomani** [comment]
reverse problem with music o_O

![screenshot00015](https://user-images.githubusercontent.com/3939543/124396982-4660e280-dd0d-11eb-9b1f-05f1b9b05e90.png)

**Comment by beatmasterRS** [comment]
https://github.com/beatmasterRS/skin.arctic.zephyr.mod/blob/ad2bc2e547c26dbbdbaa1059c15c5f51770c764b/1080i/MusicVisualisation.xml#L14-L22

especially line 

https://github.com/beatmasterRS/skin.arctic.zephyr.mod/blob/ad2bc2e547c26dbbdbaa1059c15c5f51770c764b/1080i/MusicVisualisation.xml#L18

Was the image only a fallback? then something like:

>>`<visible>!String.IsEmpty(Skin.String(fanart.fallback.music)) + [[Skin.HasSetting(musicvis.fanartfallback) + String.IsEmpty(Player.Art(fanart))] | [!Skin.HasSetting(ArtistSlideShow.Disabled) + String.IsEmpty(Window(Visualisation).Property(ArtistSlideshow.Image))]]</visible>`

could be helpfull.
Untested ^^

**Comment by Nanomani** [comment]
> Was the image only a fallback? then something like:
> 
> > > `<visible>!String.IsEmpty(Skin.String(fanart.fallback.music)) + [[Skin.HasSetting(musicvis.fanartfallback) + String.IsEmpty(Player.Art(fanart))] | [!Skin.HasSetting(ArtistSlideShow.Disabled) + String.IsEmpty(Window(Visualisation).Property(ArtistSlideshow.Image))]]</visible>`
> 
> could be helpfull.
> Untested ^^

I have post a PR :)

But I will keep your proposal carefully :D 

Anyway it is much better now : 

with stream radio fallback backgroung is used:

![screenshot00016](https://user-images.githubusercontent.com/3939543/124398458-136f1c80-dd16-11eb-80f7-c1b0f7fd87a4.png)

with music if there is fanart on local or with artist slideshow otherway fallback backgroung is used

![screenshot00017](https://user-images.githubusercontent.com/3939543/124398490-3dc0da00-dd16-11eb-87fa-61ef3baa67a4.png)
