### ISSUE TITLE
[Skin-settings] add help advice information

### ISSUE THREAD

**Issue by Nanomani** [beatmasterRS/skin.arctic.zephyr.mod#369]
only for discussion and talk ....

in Kodi there are help/advice/information here : 

![3](https://user-images.githubusercontent.com/3939543/124725948-9a3a1a00-df0d-11eb-9542-7c76203a92ff.jpg)

perhaps it will be good for user experience to have the same in skin-settings where is always "no information available" : 

![2](https://user-images.githubusercontent.com/3939543/124726233-dbcac500-df0d-11eb-993f-8de64b072ae9.jpg)

@beatmasterRS what do you think of that ?

EDIT : 
the problem i see when an option is unreachable there is no way to focus.
so no way to display a tip.

EDIT 2 : 
the second problem is that I am too bad at English to write the texts :)

**Comment by beatmasterRS** [comment]
I know the problem, but can not write english correct descriptions myself :D

**Comment by Nanomani** [comment]
So I close this issue ? :)

**Comment by beatmasterRS** [comment]
There is nothing i can help with :D So do what you wanna do :D

**Comment by Nanomani** [comment]
> There is nothing i can help with 

if I had all the texts you want to put in German that would be a good starting point. We don't ask people to write like William Shakespeare either.
I will stop boring you I think :D
