### ISSUE TITLE
[Background] issue with background, when slide out animation is enabled

### ISSUE THREAD

**Issue by beatmasterRS** [beatmasterRS/skin.arctic.zephyr.mod#376]
@Nanomani maybe if you like and have time, you could have a look at the background-code. I think the fallback-image or the image, you can set as a background in skinshortcuts is not properly shown, when control 2011 is focused. 

I searched for another solution, not to use a hidden button, but when using properties, the usability is not good in my eyes, as you can see/test with the branch here:

>>https://github.com/beatmasterRS/skin.arctic.zephyr.mod/tree/homemenu-feature-1.2

The currrent behaviour seems to have a good usability for me, as when the menu gets fade out and you focused "movies" and i fades in, the focus is also on "movies". Thats imho fine.

As you can see in the releated PR:

>>https://github.com/beatmasterRS/skin.arctic.zephyr.mod/pull/368/files 

the button 2011 gets focused after a few seconds and when button 2011 has focus, an animation is triggered.

Thanks a lot :)

**Comment by Nanomani** [comment]
I m agree with you I prefer the current behaviour :)

But I see nothings special when control 2011 is focused. 
fallback-image  or background  set with skinshortcuts are correctly display

perhaps a screenshot can help ?

**Comment by beatmasterRS** [comment]
It seems so. Unfortunately, I could not test it yet.

The description of the issue, translated with deepl.com

>>With the latest Git version and the automatically hiding main menu, the error with the background image exists again.
As long as the main menu is displayed and e.g. the tab Series is selected, the background image I set for it is displayed.
If the main menu is now hidden after a few seconds, the background image changes as if I would select the upper left entry of the set widget.

**Comment by Nanomani** [comment]
ok thanks.
fix is possible :)
I post PR soon I think :)

**Comment by Nanomani** [comment]
Must be fixed now :)

**Comment by Nanomani** [comment]
Sorry I see only now your post in forum :D

**Comment by beatmasterRS** [comment]
No problem :D
