### ISSUE TITLE
Hub picture

### ISSUE THREAD

**Issue by MeirB88** [beatmasterRS/skin.arctic.zephyr.mod#379]
Hi, first of all amazing work!
I would really like to be able to change the custom hub items image. is it possible to add this feature/explain how to do it?

**Comment by beatmasterRS** [comment]
WhichiImage do you mean? Screenshots could be helpful. Thanks

**Comment by MeirB88** [comment]
![screenshot00003_LI](https://user-images.githubusercontent.com/25164014/125084655-72e07a00-e0d2-11eb-996a-99df327f0379.jpg)
That image, for custom hub items

**Comment by beatmasterRS** [comment]
Currently the are'nt any plans to add an option for that. But you can edit the code to your needs. Just take a look here:

https://github.com/beatmasterRS/skin.arctic.zephyr.mod/blob/3d0070e0e2b37c6e9cf9f1cb23b41c20c5c8b9e4/1080i/Includes_Defs.xml#L815
