### ISSUE TITLE
[plugin.video.itunes_podcasts] improvement with "Play Now Info" or "Music Visualisation"

### ISSUE THREAD

**Issue by Nanomani** [beatmasterRS/skin.arctic.zephyr.mod#383]
for myself :)

plugin.video.itunes_podcasts

GIT : https://github.com/A600/plugin.video.itunes_podcasts/
ZIP : https://github.com/A600/plugin.video.itunes_podcasts/archive/refs/heads/Matrix.zip

I don't know if something is possible ?

"plugin.video.itunes_podcasts"  with Widgets (script.skinshortcuts) all works very fine
there are "title", "plot", "thumb"

![screenshot00000](https://user-images.githubusercontent.com/3939543/125140208-49474300-e112-11eb-93da-b10168e76e75.png)

with "play now info" or "Music Visualisation" there is no info at all

![screenshot00002](https://user-images.githubusercontent.com/3939543/125140454-d12d4d00-e112-11eb-8fb1-906e57fa8d0e.png)

![screenshot00001](https://user-images.githubusercontent.com/3939543/125140462-d5596a80-e112-11eb-842e-80daa541c873.png)

any advice are welcome :)
thanks

**Comment by beatmasterRS** [comment]
Are the releated "MusicPlayer" infolabels filled by the addon?

**Comment by Nanomani** [comment]
With all the tests I have done, it looks like it's not or not correctly.

eg : 
$INFO[MusicPlayer.Title]         => "https://url/file.mp3
$INFO[Player.Art(thumb)]        => EMPTY

**Comment by beatmasterRS** [comment]
Then it is up to the addon developer

**Comment by Nanomani** [comment]
> Then it is up to the addon developer

You are right.  thanks for your advice.
I'm going to ask him the question. :)
https://forum.kodi.tv/showthread.php?tid=143064

wait and see
in any case it allows me to learn ...

**Comment by Nanomani** [comment]
for podcast audio this works well : 

$INFO[VideoPlayer.Plot] => Plot
$INFO[VideoPlayer.Title] => Title

no solution for the thumbnail :

$INFO[Player.Icon] => EMPTY
$INFO[Player.Art(thumb)] => EMPTY

only this : 

System.AddonIcon(plugin.video.itunes_podcasts) :/

**Comment by beatmasterRS** [comment]
> for podcast audio this works well :
> 
> $INFO[VideoPlayer.Plot] => Plot
> $INFO[VideoPlayer.Title] => Title

It is an addon for audio and video podcasts?

**Comment by beatmasterRS** [comment]
Ah okay, i have seen in the OT in kodi forum.

**Comment by Nanomani** [comment]
> > for podcast audio this works well :
> > $INFO[VideoPlayer.Plot] => Plot
> > $INFO[VideoPlayer.Title] => Title
> 
> It is an addon for audio and video podcasts?

audio and video 

![1](https://user-images.githubusercontent.com/3939543/125204019-719e8100-e27b-11eb-8c04-94b38ff793e5.jpg)

I m only use audio podcasts

**Comment by Nanomani** [comment]
no clean or correct solution : /

**Comment by beatmasterRS** [comment]
Sadly not :I
