### ISSUE TITLE
Addon zoom preview screenshot must be fanart not square

### ISSUE THREAD

**Issue by Nanomani** [beatmasterRS/skin.arctic.zephyr.mod#386]
with estuary

![screenshot00001](https://user-images.githubusercontent.com/3939543/125433952-56bd645d-06b8-4bf8-9e09-9c56df4c1d14.png)

with AZ2

![screenshot00003](https://user-images.githubusercontent.com/3939543/125433996-fa169165-2a30-4c37-88d9-cf15da8536d7.png)

**Comment by beatmasterRS** [comment]
There are currently only 2 aspect ratios in these lists: poster and square. It just didn't look good when zoomed to the same size top have consistency, because the fanart covered a lot of the screen. Therefore, for Youtube videos, there are also only squares as aspect ratio. :)

**Comment by Nanomani** [comment]
Oops I had never seen that we could display the thumbnail in full screen :D
So this issue is just cosmetique  issue. This issue can be closed. Not sure that spend to time for that is necessary :)
