### ISSUE TITLE
Libreelec (probably Coreelec too) impossible to focus

### ISSUE THREAD

**Issue by Nanomani** [beatmasterRS/skin.arctic.zephyr.mod#387]
reproduce : 

![screenshot00005](https://user-images.githubusercontent.com/3939543/125434850-e666316f-b51f-43bb-b35a-f08837af4229.png)

![screenshot00006](https://user-images.githubusercontent.com/3939543/125434879-317f7e2e-eaac-415a-be6b-2c1d35392345.png)

![screenshot00008](https://user-images.githubusercontent.com/3939543/125434969-18b73526-2fd1-4a61-927b-bb99bf6810f9.png)

**Comment by beatmasterRS** [comment]
Please try to click to the right, then the buttons should be focused. For me this works. Nevertheless, the save/cancel dialog would have to be adapted to the current design :)

**Comment by beatmasterRS** [comment]
Please test :)
