### ISSUE TITLE
weather icon overlaps with the clock

### ISSUE THREAD

**Issue by Kampfader** [beatmasterRS/skin.arctic.zephyr.mod#4]
see pic
![screenshot000](https://user-images.githubusercontent.com/23200748/51794126-76b30700-21cc-11e9-8ecc-c72bc0d6284d.png)

**Comment by IanWONeill** [comment]
I think this will be an issue with using different resolutions, seems fine on mine but squashed on yours. Hopefully @beatmasterRS will be able to resolve this issue.

**Comment by beatmasterRS** [comment]
I will look at this in the next few days. As I remember, positioning of this was a little bit tricky, but I'm sure, I can fix this issue soon.

**Comment by beatmasterRS** [comment]
should be fixed
