### ISSUE TITLE
Issues, that needs to be fixed till next update on Sunday the 25th 

### ISSUE THREAD

**Issue by beatmasterRS** [beatmasterRS/skin.arctic.zephyr.mod#410]
I'm planning the next update within the next few days, a week, i think. :) It would be good if we could fix as many bugs as possible until the next release, since in the official repo the update intervals are a bit longer. If critical bugs appear then, that would be a problem. 

You won't be able to fix all the problems, but it would be nice if the most important ones were fixed. Then we have a stable version where we can add new features without thinking about possible old bugs. Currently i am on the way, fixing a possible bug with fullsize fanart. https://forum.kodi.tv/showthread.php?tid=337862&pid=3050403#pid3050403

If you notice any issues, please let me know, or if you like, submit a PR. Any help is very welcome.

Thanks a lot for all of your effort! <3

@Nanomani 
@fabricionaweb 
@semool

**Comment by Nanomani** [comment]
Bad news. Actually I have seen nothing to be need fixed :)

**Comment by beatmasterRS** [comment]
Thanks for your feedback :)

**Comment by beatmasterRS** [comment]
I will do a version bump on Sunday the 25th and submit the update :)

**Comment by beatmasterRS** [comment]
Do you have any things, that need to be included/changed? Or can i submit the update?

**Comment by Nanomani** [comment]
I have a issue who can wait ...
So let's go for the update :)

**Comment by beatmasterRS** [comment]
Now I am at work :D I will submit, when I am back home :D
