### ISSUE TITLE
Logo "Arctic" Zephyr with "skin-settings" need to be linked with mode day/night

### ISSUE THREAD

**Issue by Nanomani** [beatmasterRS/skin.arctic.zephyr.mod#414]
by default if "night/dark" it is good

not if "day/light"

![screenshot00022](https://user-images.githubusercontent.com/3939543/126466642-6676bed9-e8f0-4e26-8b5a-cc72f2813cce.png)

**Comment by beatmasterRS** [comment]
Should be fixed now :)
