### ISSUE TITLE
Litebox, after Update

### ISSUE THREAD

**Issue by beatmasterRS** [beatmasterRS/skin.arctic.zephyr.mod#417]
>>Enable effects = Skin.HasSetting(BlurEnabled )

This is only releated to users, which have blur enabled and got the new update with litebox.

After updating to the next version, litebox is used for effects. If the user has BlurEnabled setting, no effect and no background will be visible, cause litebox isn't running after skin update. Litebox is only running, if effects will be enabled through skin settings, or if effects are enabled and kodi will be restarted. 

After the update, the user opens the skin settings, cause no blured background is visible, and will find that, if effects were enabled:

![screenshot00319](https://user-images.githubusercontent.com/3855273/126509319-ecc8b823-5ac7-4d84-9b38-425f2fb7d097.png)

The following options for users:

- restarting kodi and all will be fine
- disable and enable effects and litebox will start, settings got enabled and user can choose options 
- but maybe not every user knows what to do

Options for us to avoid this behaviour

- rename "BlurEnabled" setting to e.g. "BlurEnabledLitebox" and after the update, blur will be disabled, cause "BlurEnabledLitebox" is false. The user can enable the setting and litebox will start. This is also better for embuary.helper script, cause "BlurEnabled" setting triggers the blur function of embuary.helper.

There is no easy way. But it would be good if there is a way that would be better.

What do you think? Have you a better idea? :) I hope, you know, what i mean :D

@Nanomani

**Comment by Nanomani** [comment]
I know perfectly what you mean. :)

I think renaming "BlurEnabled" to "BlurEnabledLitebox" in the code is a good compromise.
Then add a small warning in the forum the day of the update in repo kodi to indicate : 

`the update from 1.1.55 to 1.1.56 may require to enable again the "blur" effect`
`sorry for the inconvenience. This will only be needed once and only with this update`
blah blah blah :D

I think it's hard to do better :)

**Comment by beatmasterRS** [comment]
Sound's good, thank you :)
