### ISSUE TITLE
Hide completely menu for Vertical like Modern when slide out

### ISSUE THREAD

**Issue by Nanomani** [beatmasterRS/skin.arctic.zephyr.mod#423]
Not really a bug more a request because I love clean and minalism. :)
With "Vertical Multi-widget / netflix" layout when menu on left slide this is always a bit visible.

![screenshot00001](https://user-images.githubusercontent.com/3939543/126866063-aee94e88-26a2-4e01-bf7a-b8b90d9bc509.png)

It will be cool if the menu become completely hide like "Modern Multi-widget / netflix" layout.
this is also better for consistancy :D

Like always feel free to close this if not simple, accepted, or other ... :)

**Comment by beatmasterRS** [comment]
Maybe we could include this in the "more minimal & clean" setting?

**Comment by Nanomani** [comment]
> Maybe we could include this in the "more minimal & clean" setting?

Yes it is a good idea if others people prefer keep this like that :)

**Comment by beatmasterRS** [comment]
For the vertical there is currently no use, when "more minimal & clean" is enabled, right?

**Comment by Nanomani** [comment]
> For the vertical there is currently no use, when "more minimal & clean" is enabled, right?

Yes right

**Comment by beatmasterRS** [comment]
Ah i see it. Ok cool then a PR is always welcome :)

**Comment by Nanomani** [comment]
I have so many things to learn...
But If I can make a serious and clean PR, with pleasure I will do.

**Comment by beatmasterRS** [comment]
I can do that too, but currently I don't have time, because I would like to submit the update on Sunday...

**Comment by Nanomani** [comment]
Yes of course, no problem :)

**Comment by Nanomani** [comment]
And if I can help ... But I see nothing to do :)

**Comment by beatmasterRS** [comment]
What i would like to improve is the playlist info on the left...

![screenshot00405](https://user-images.githubusercontent.com/3855273/126870376-45b3846a-e703-470b-9371-b4b77ae830a8.png)

Everytime i select a song, the list jumps up or down and the playing song is not on the same position...

**Comment by beatmasterRS** [comment]
But there is no solution for that i think...
