### ISSUE TITLE
[Playlist Music] OSD don't display track information if playlist created from folder

### ISSUE THREAD

**Issue by Nanomani** [beatmasterRS/skin.arctic.zephyr.mod#425]
To reproduce : 

1. Open Music folder in file mode : 

![screenshot00000](https://user-images.githubusercontent.com/3939543/126906676-f8fc2a20-a02d-4597-816d-485d990114b9.png)

eg : folder "Pop Rock" folder contains 29 albums

![screenshot00001](https://user-images.githubusercontent.com/3939543/126906682-b89da25a-3b0f-43a4-9378-5a4a9aba8624.png)

2. open context menu from a folder, select "queue item"

![screenshot00002](https://user-images.githubusercontent.com/3939543/126906767-01f5e4cd-f3d8-4473-afda-99edf212ca65.png)

3. music is playing like expected : 

![screenshot00004](https://user-images.githubusercontent.com/3939543/126906829-58f96d33-d5d8-4054-9145-5bcfe0ff8224.png)

4. in OSD : 
 - the tracks are not displayed correctely
 - number of song displyed is wrong. It is the number of albums

![screenshot00003](https://user-images.githubusercontent.com/3939543/126906834-a149bd42-7b7a-49a8-a27b-179a51246945.png)

Perhaps it is not possible to fix this. It is worth a try.
It will be cool if this could works correctely :)

**Comment by beatmasterRS** [comment]
I also have his issue sometimes and I don't know, what causes this. I don't know if it's skin releated.

**Comment by Nanomani** [comment]
> I also have his issue sometimes and I don't know, what causes this. I don't know if it's skin releated.

This issue is for me :D

**Comment by beatmasterRS** [comment]
I have tested this with other skins. There, the issue also exists, so i think, it's not skin releated...

**Comment by Nanomani** [comment]
With Estuary all works very well :)

![screenshot00008](https://user-images.githubusercontent.com/3939543/126972981-746ad950-5b8d-491b-9fab-4966293aad20.png)

![screenshot00009](https://user-images.githubusercontent.com/3939543/126972995-7e185017-39c7-4e11-9704-091eac0e794c.png)

![screenshot00010](https://user-images.githubusercontent.com/3939543/126973000-e6cfd9f7-8fc5-42cf-a262-6436d349b545.png)

![screenshot00011](https://user-images.githubusercontent.com/3939543/126973038-24247f0b-6b0b-49d6-a3af-cae654a3d5bf.png)


![screenshot00006](https://user-images.githubusercontent.com/3939543/126972823-c83eb59e-ce7c-47cb-901b-fc418c9cce3a.png)

**Comment by Nanomani** [comment]
I don't have time now. 
But I'm sure some improvement in the code is possible / necessary

**Comment by Nanomani** [comment]
I have add a button "playlist" in OSD music only for my need and some tests not linked with this issue :)
Everytime I display "playlist" then i go back to OSD all tracks are correctely displayed. :D

![3](https://user-images.githubusercontent.com/3939543/127131553-cc391d67-e9e8-458b-961c-cd88266711d1.jpg)

![4](https://user-images.githubusercontent.com/3939543/127131574-e8ab97df-8474-4d68-9a28-0211bab83cc6.jpg)

![5](https://user-images.githubusercontent.com/3939543/127131587-6e6c5f36-80e6-4557-92f0-392b9d280268.jpg)

**Comment by beatmasterRS** [comment]
Exactly this behavior I have also noticed in my tests :D

**Comment by Nanomani** [comment]
ok i think it is better now that i go fishing :D
