### ISSUE TITLE
[MusicOSD] improvements playlist access

### ISSUE THREAD

**Issue by Nanomani** [beatmasterRS/skin.arctic.zephyr.mod#428]
With 1.1.56 the navigation with OSD music is bit more limited.
For people who want access tracks already played, they can : 

- reopen playlist/album. not friendly
- use the default keymap "n" for open current "playlist". not possible with limited remote
- use addons "keymap". not friendly for the begginer

so add button "show playlist" in OSD seems good for everybody :)

if agree I post a PR

**Comment by beatmasterRS** [comment]
Sound s good :)
