### ISSUE TITLE
[Skin Settings] in "supported addon" when addon is "disable" it is not displayed correctly 

### ISSUE THREAD

**Issue by Nanomani** [beatmasterRS/skin.arctic.zephyr.mod#436]
![10](https://user-images.githubusercontent.com/3939543/127766428-b0fdf32b-6a83-4a8c-87d1-fc2033388503.jpg)

**Comment by beatmasterRS** [comment]
Should be fixed now :)

**Comment by Nanomani** [comment]
Yes
you are too fast for me.
I was going to post the same PR :)
