### ISSUE TITLE
[Video] subtitle / audio offset setting not displayed correctly

### ISSUE THREAD

**Issue by Nanomani** [beatmasterRS/skin.arctic.zephyr.mod#442]
Before 

![screenshot00007](https://user-images.githubusercontent.com/3939543/127783546-5bf8a6ee-199e-4386-b6e8-c668f4a51377.png)

now 

![screenshot00009](https://user-images.githubusercontent.com/3939543/127783577-62efb621-a1d2-455f-8806-a38a66cb1e76.png)

**Comment by Nanomani** [comment]
With PC => no issue with all version AZR

With Linux (Libreelec)  
AZR 1.1.55 => no issue
AZR 1.1.56 => there is this issue

**Comment by Nanomani** [comment]
I got it :)

AZR 1.1.56 from GITHUB  have the issue
AZR 1.1.56 from REPO KODI have no issue

the difference is when files media are compressed or not
Compressed (Textures.xbt) => no issue
Not compressed => there is this issue

**Comment by beatmasterRS** [comment]
Should be fixed now: https://github.com/beatmasterRS/skin.arctic.zephyr.mod/commit/c1b9f1c34a4547d2808703761661e799c565c57d

Its the same behaviour with a commit, a few days ago. There i have noticed the same: https://github.com/beatmasterRS/skin.arctic.zephyr.mod/commit/3aa2134ae305d2d8149efcde6fb48ec59de7b1b8

**Comment by beatmasterRS** [comment]
Its an an uppercase / lowercase problem, like you have mentioned :)

**Comment by Nanomani** [comment]
thanks a lot for your feedback :)
