### ISSUE TITLE
[Feature Request] - Option to make Notification dialog transparent and choose allignment

### ISSUE THREAD

**Issue by Rouzax** [beatmasterRS/skin.arctic.zephyr.mod#459]
Also put this one in through the forum, but thought it would be better to put it here for traceability.

Would it be possible to have 2 additional options?

1. Make Notification dialog transparent with gradient shading like in Arctic Zephyr 2
![image](https://user-images.githubusercontent.com/4103090/129312924-b10b8303-d813-499c-b42b-c88c6c9bc04f.png)

2. Have an option to align left instead of right. My LG TV will show things like HDR dialog etc on the right side, overlapping the Notification dialog.

I'm using LazyTV as an addon to random start the first unwatched episode of TV shows. LazyTV will trigger a Now Playing Notification on the start of the episode, which I can't read since my TV is also switching to HDR and showing that label.

**Comment by beatmasterRS** [comment]
Thanks for your request. A:Z - R has a clear design line, which e.g. means that all notification boxes are shown on the top right. When I'm e.g. in the home menu, myvideonav or in the settings, what is now playing is shown on the top right. If this would now be shown in fullscreen window on the top left, it would be more than inconsistent.

**Comment by Rouzax** [comment]
I understand, still had to try 😀
