### ISSUE TITLE
[Feature Request] - Option to remove player controls from OSD.

### ISSUE THREAD

**Issue by Rouzax** [beatmasterRS/skin.arctic.zephyr.mod#460]
Would it be possible to add an option to remove the player controls from the OSD?

I'm using Kodi on my TV with a remote that has all those buttons, when ever I need to navigate to that OSM menu it is to do something specific like time sync Subtitles or open extra info.
With the addition of all those buttons it takes a lot of lefts or rights to get to the desired menu selection.

![image](https://user-images.githubusercontent.com/4103090/129313708-f15a534b-17ef-4ae1-b0f8-c126b99cf841.png)

**Comment by beatmasterRS** [comment]
Thanks for your request. To be honest, I will not implement such an option, as I think that there is no need to add an option because of every little change and the skin already has countless options. Besides, the skin has 3 different OSD types.

**Comment by Rouzax** [comment]
I understand.
What is the main difference between the default and reloaded OSD?
Can't find much difference beside the hight.

**Comment by beatmasterRS** [comment]
>>Can't find much difference beside the hight.

Sorry, but I see a few more differences there than just the height:

![screenshot00492](https://user-images.githubusercontent.com/3855273/129345605-efbfe58b-5360-412d-9099-4ed5ed515539.png)

![screenshot00493](https://user-images.githubusercontent.com/3855273/129345846-ce859bac-5468-4488-a591-e2cf17ef6432.png)
