### ISSUE TITLE
How to change the  "seeking bar" postion?

### ISSUE THREAD

**Issue by fireflycao** [beatmasterRS/skin.arctic.zephyr.mod#461]
I just want the "seeking bar" is not at bottom, so  i can see the sub when i push the left or right on the remote

**Comment by beatmasterRS** [comment]
Just take a look at https://github.com/beatmasterRS/skin.arctic.zephyr.mod/blob/master/1080i/DialogSeekBar.xml

**Comment by fireflycao** [comment]
copy it to '\Addons\skin.arctic.zephyr.mod\1080i'?

**Comment by beatmasterRS** [comment]
No, this is the file used for the seek bar.
