### ISSUE TITLE
[Request] playlist button

### ISSUE THREAD

**Issue by deyooluv** [beatmasterRS/skin.arctic.zephyr.mod#466]
Please can you add the playlist button on the video osd

**Comment by beatmasterRS** [comment]
Will not be added as an icon but _maybe_ as an entry in the osd settings. We will see.

**Comment by deyooluv** [comment]
> Will not be added as an icon but _maybe_ as an entry in the osd settings. We will see.
Sounds good. Looking forward to it. Thank you

**Comment by deyooluv** [comment]
> Will not be added as an icon but _maybe_ as an entry in the osd settings. We will see.

Sounds good. Looking forward to it. Thank you

**Comment by beatmasterRS** [comment]
Bad news: i have not found a solution for adding a videoplaylist- entry in the osd settings, sorry.
