### ISSUE TITLE
Seek Bar does not display when seeking

### ISSUE THREAD

**Issue by KingSalehZar** [beatmasterRS/skin.arctic.zephyr.mod#481]
The seekbar would display when you play a music for a few seconds and then it disappears. It does not comeback while seeking. If this can be fixed it would be appreciated.

**Comment by beatmasterRS** [comment]
Please test https://github.com/beatmasterRS/skin.arctic.zephyr.mod/archive/refs/heads/music-osd-patch-1.zip
