### ISSUE TITLE
Live TV OSD is drawn twice

### ISSUE THREAD

**Issue by beanaroo** [beatmasterRS/skin.arctic.zephyr.mod#499]
Firstly, thank you for such an amazing project!

---

- Kodi 19.1
- IPTV Simple 7.6.10
- Arctic Zephyr 1.1.58

#### Navigating up and down while watching shows the OSD as expected:
![screenshot00001](https://user-images.githubusercontent.com/1748909/132936740-c90cd1fa-9ec1-4663-aa0b-1c87ef284cb3.png)

#### Switching to a channel, or pressing info while watching, presents what looks like two OSDs drawn over each other:
![screenshot00003](https://user-images.githubusercontent.com/1748909/132936782-c46dd5ae-1b30-4156-8868-a7fa8104ddd3.png)

One appears to have the Channel Icon in Poster aspect, which causes it to be cropped.

I tried various settings for both the skin, player and PVR client with no success.

**Comment by beatmasterRS** [comment]
Unfortunately, I can't reproduce the issue you mentioned.

Could you please provide your userdata\addon_data\skin.arctic.zephyr.mod\settings.xml file?

**Comment by Nanomani** [comment]
@beatmasterRS FYI I have the same. 
I can live with it so I never said anything about it :)
When I have some time and motivation I will check that

![screenshot00008](https://user-images.githubusercontent.com/3939543/133452327-0211d5c2-1ae0-4c38-a870-31be23dc54bd.png)

**Comment by JC253** [comment]
I've also had this issue for a very long time. Hoping one day it can be fixed. Thanks

**Comment by Nanomani** [comment]
If someone want test :  

ZIP: https://github.com/Nanomani/skin.arctic.zephyr.mod/archive/refs/heads/fix-liveTV-display-OSD.zip

All feedback are welcome :)
Thanks

**Comment by JC253** [comment]
> @JC253 @beanaroo
> 
> If someone want test :  
> 
> ZIP: https://github.com/Nanomani/skin.arctic.zephyr.mod/archive/refs/heads/fix-liveTV-display-OSD.zip
> 
> All feedback are welcome :)
> Thanks

Thanks, but I just left to go to work. I'll text when I get home tonight. I'll check back later to see how it's working for the rest of you. 
Thank you!

**Comment by Nanomani** [comment]
> Thanks, but I just left to go to work. I'll test when I get home tonight. I'll check back later to see how it's working for the rest of you.
> Thank you!

Thanks for your feedback :)
