### ISSUE TITLE
Issues with multiple sources. 

### ISSUE THREAD

**Issue by ShadoUrufu** [beatmasterRS/skin.arctic.zephyr.mod#519]
I'm going to link the forum convo for some of the context: [Link](https://forum.kodi.tv/showthread.php?tid=364448&pid=3060290#pid3060290)

I do hope I'm sending this at the right place. Anyway, the issue i have is that I'm trying to load a library that has two sources, as a menu item. Worked on my laptop, but idk which version it had and I can't check it since the hard drive died on me. I'm running into the issue on version 1.1.58 and 1.1.59, which i just installed before making this. 

Anyway, when I try to link the multi-source to the menu, it just refuses to work, despite me choosing the 'create from here' option. When i get to it, i see [this](https://cdn.discordapp.com/attachments/352590803488604171/887741947597455441/unknown.png) which is not what I usually see with the single-path sources. I only see the 'create from here' option in those. 
After goign through the normal selections, I am returned to [this.](https://cdn.discordapp.com/attachments/352590803488604171/887742332290629652/unknown.png)

Which is essentially the menu acting as if nothing happened. Attempting to add the extra source after I made the menu item also breaks the system, whereas it doesn't load the new content, and often stops registering changes to the old stuff as well. Almost as if the fact that it's seeing two different paths is creating some kind of conflict with the source library. 

I've tried with other skins, and the source itself doesn't seem to have any issues.

**Comment by ShadoUrufu** [comment]
I am using a smart playlist, but setting a smart playlist as the menu item does not work how i want it to. Specifically how I can't get it to point to two different locations to get media from. That, and I do not want to make two playlists for every menu items, since I'm using the smart playlist method for the spotlight feature, and telling it to not show watched content, and to only point to a specific location. 

I feel like setting up a system of smart playlists for the menu items is far more confusing, and far more work, than simply telling the source to point to two different location where I have the media I want to be shown. 

In this case, My Japanese audio anime are on two hard drives. Because the main one is too small for all of it by 70gb, and the other one is already filled with everything else. This system worked before, and now it doesn't, and I've done the exact same thing as I did when I set it up on the laptop. 


Another reason why I want multiple paths for a source, is in cases where I may not want to include certain folders. but for PC organization, i prefer everything to be in the same place when i need to move things in bulk.

**Comment by ShadoUrufu** [comment]
Alright well, tried tome stuff with the playlist, and trying to link from my source with multiple paths does nothing. So the issue is likely with the multipath command used for the sources.

**Comment by beatmasterRS** [comment]
How does it work in other skins? What's the difference? Screenshots could be helpful

**Comment by ShadoUrufu** [comment]
It does not exactly work on other skins. But I'll get you some screenshots anyway. 
These were taken using Rapier: [Top of the list, shows 11eye which is on one drive](https://cdn.discordapp.com/attachments/352590803488604171/887792723816513576/unknown.png)
[Bottom of the list, showing Yuuna's Hotspring which is on the other drive.](https://cdn.discordapp.com/attachments/352590803488604171/887792916100173854/unknown.png)

I haven't been able to configure Rapier all that much, this just takes all of the 'TV shows' and shoves them into one category. 

[And here's Esuary, the default skin, I'm browsing media sources.](https://cdn.discordapp.com/attachments/352590803488604171/887793710606196796/unknown.png)

**Comment by ShadoUrufu** [comment]
I haven't figured out how to make separate menu items for those other skins. Only zephyr seems to make that easy. And I like the way the skin looks.

**Comment by beatmasterRS** [comment]
Sorry, but what do you mean with source with multiple paths? Please provide screenshots of all releated things, using this skin.

**Comment by ShadoUrufu** [comment]
[This is the source that fails. And how I set it up using my laptop.](https://cdn.discordapp.com/attachments/352590803488604171/887803279013208124/unknown.png)

**Comment by beatmasterRS** [comment]
Thanks a lot. It's not a skin releated issue. Is the media correctly scraped into the library?

**Comment by ShadoUrufu** [comment]
As far as i can tell, yes, other than maybe brigadoon. Though I sometimes run into some shows that need to be adjusted because of bad metadata. Mostly due to how i named the files, or things like two series with the same name getting confused. Like Full Metal Alchemist, and FMA Brotherhood

The source works as it should, as a source. It's just when i try to link a menu item, specifically this one that has two paths(as shown in the pic) that it freaks out.

**Comment by ShadoUrufu** [comment]
It's still skin related, as far as I can tell. I'm using the skin's settings to setup the home menu panel.

**Comment by beatmasterRS** [comment]
That's still not a skin releated issue, nor a bug, that is skin releated.
