### ISSUE TITLE
Auto-playing trailers

### ISSUE THREAD

**Issue by trkselim** [beatmasterRS/skin.arctic.zephyr.mod#530]
Hi
Auto-playing trailers for widgets in home screen, is that when kodi's starts playback/stops for a trailer it auto-refreshes the widgets.
This makes the widget change content sometimes (depends on the sort method) as the trailer is playing and slows the UI experience significantly.

Would it be possible to add option for disabling widget’s auto- refresh.

thanks in advance

**Comment by beatmasterRS** [comment]
I already implemented a switch to mostly prevent this behaviour:

    <variable name="RandomMovies">
        <value condition="Skin.HasSetting(home.netflix.autoplay.trailer) + System.AddonIsEnabled(service.library.data.provider) + ![Skin.HasSetting(EnableEffects) + Skin.HasSetting(BlurOnHome)]">plugin://service.library.data.provider?type=randommovies&amp;reload=$INFO[Window.Property(randommovies)]</value>
        
        <value condition="Skin.HasSetting(home.netflix.autoplay.trailer)">special://skin/extras/playlists/Spotlight.xsp</value>
        <value>special://skin/extras/playlists/RandomMovies.xsp</value>
    </variable>

Unfortunately I can't do more, because I can't control the behavior of Kodi itself.
