### ISSUE TITLE
Spotlight like something like this in Cosmic!

### ISSUE THREAD

**Issue by Whiteripd0** [beatmasterRS/skin.arctic.zephyr.mod#543]
I am infinitely grateful to you for this skin!  He is simply ideal and nothing will be better in terms of elegance and accuracy.  I would like to know if it is possible to add the "Spotlight" function, but not the same as in Netflix, but as in Cosmic :) It would be great if, when the trigger was pressed on the movie, the "Spotlight" window with a larger logo and slogan of the movie was called up .. It would not be  did not affect the overall screen but would give a great opportunity. I really like your aesthetically elegant skin but I like this feature the same way ..) I wanted something like that in Zephyr. 

I also wanted to write to you about the problems that I encountered while using.  1) For some reason, the function "Try to lock skin colors / the / fonts" don't work.  It is grayed out unfortunately (2) In the widgets, when you click Dialoginfo, the next page is not clicked in the movie recommendations tabs. I added it to my favorites but that didn't solve the problem. I checked it everywhere, but in other skins it works without any problems .. And also insignificant, but still) When playing a movie, there is no discart, but in the information itself it is present and in the player settings it is turned on) Thanks in advance!

**Comment by Whiteripd0** [comment]
I also wanted to write to you about the problems that I encountered while using.  1) For some reason, the function "Try to lock skin colors / the / fonts" don't work(  It is grayed out unfortunately (2) In the widgets, when you click Dialoginfo, the next page is not clicked in the movie recommendations tabs. I added it to my favorites but that didn't solve the problem. I checked it everywhere, but in other skins it works without any problems .. And also insignificant, but still) When playing a movie, there is no discart, but in the information itself it is present and in the player settings it is turned on) In general, everything else is perfect:) None  I didn't notice any more problems!

**Comment by Nanomani** [comment]
> 1) For some reason, the function "Try to lock skin colors / the / fonts" don't work. It is grayed out unfortunately

this setting must be enable :  

![1](https://user-images.githubusercontent.com/3939543/134763457-212b87ec-73d4-439f-bda8-cd425b9af88f.jpg)

**Comment by Whiteripd0** [comment]
Yesterday I somehow solved the problem with this and now this blocking function works again.  But the above two problems still don't work. Next page in DialogVideo and Favourite..

**Comment by beatmasterRS** [comment]
> I am infinitely grateful to you for this skin! He is simply ideal and nothing will be better in terms of elegance and accuracy. I would like to know if it is possible to add the "Spotlight" function, but not the same as in Netflix, but as in Cosmic :) It would be great if, when the trigger was pressed on the movie, the "Spotlight" window with a larger logo and slogan of the movie was called up .. It would not be did not affect the overall screen but would give a great opportunity. I really like your aesthetically elegant skin but I like this feature the same way ..) I wanted something like that in Zephyr.

I don't think there will ever be such a Spotlight dialog, because each skin has its own design language. It is unfortunately already the case that some skins (including AZ: R) look more and more like others and only a few skins have their own design language. Therefore no ;)

> (2) In the widgets, when you click Dialoginfo, the next page is not clicked in the movie recommendations tabs. I added it to my favorites but that didn't solve the problem. I checked it everywhere, but in other skins it works without any problems .. 

In which skin is an online content list in dialog info with a "next page" item?

> And also insignificant, but still) When playing a movie, there is no discart, but in the information itself it is present and in the player settings it is turned on) 

Unfortunately, I cannot reproduce the issue, you hav mentioned. If the setting for DiskArt is enabled, discart is shown for me:

![screenshot00597](https://user-images.githubusercontent.com/3855273/134771866-e531bb1d-711e-453e-8ef1-69bfb875b4eb.png)

![screenshot00598](https://user-images.githubusercontent.com/3855273/134771871-a38320ee-3739-4298-afa2-dba18a6cfed5.png)

**Comment by Whiteripd0** [comment]
No hard feelings!  :) I understood and heard you) It's a pity of course that this will never happen in Zephyr, but I still like it very much without it) (2) The problem with the next page .. I checked it everywhere and it works without problems.  When you go to DialogInfo, the next page is not pressed and this is in all skins.  But for this I added favorites to the menu section to go to the next page.  In Zephyr it works like this: if you go to the recommendations in the widgets and click the next page, it still does not work, and even if you add to favorites it still does not work, unlike other skins .. But in Zephyr it only works if you do not go to  widgets and in the library of films / series itself, and then if you add the next page to your favorites, it works.  I would very much like the button to be functional in the widgets as well) And by the way I wanted to know if it is possible in DialogInfo to add recommendations based on recommended films and not similar ones, since I noticed that there is a higher percentage of hits by similarity :) For example, I noticed that with comedies  in similar films, he shows horror movies and detectives😅

**Comment by beatmasterRS** [comment]
> But for this I added favorites to the menu section to go to the next page. In Zephyr it works like this: if you go to the recommendations in the widgets and click the next page, it still does not work, and even if you add to favorites it still does not work, unlike other skins .. 

In which skin is an online content list in dialog info with a "next page" item?

**Comment by beatmasterRS** [comment]
Please test the latest master from here:

https://github.com/beatmasterRS/skin.arctic.zephyr.mod/archive/refs/heads/master.zip

**Comment by Whiteripd0** [comment]
Sorry, unfortunately I don't really understand .. But I mean in Zephyr.  Sorry, I don't even know how to answer .. I don't really understand what you mean :( But the bottom line is that the Next page button does not work with widgets, but only works with the library, but this is subject to adding Next page to the Favorites section *

**Comment by Whiteripd0** [comment]
Now it shows 20 movies and the next page button is missing.  It looks better of course)) But I like to flip through the pages of similar films :)

**Comment by Whiteripd0** [comment]
By the way, now % of hits of recommended movies are 100% :) Thank you so much for fixing it!  You made my day ^^

**Comment by Whiteripd0** [comment]
Now it shows 20 movies and the next page button is missing.  It looks better of course)) But I like to flip through the pages of similar films :) By the way, now% of hits of recommended movies are 100% :) Thank you so much for fixing it!  You made my day ^^
