### ISSUE TITLE
[Request] Auto-hide Menu Bar Items Fix

### ISSUE THREAD

**Issue by JC253** [beatmasterRS/skin.arctic.zephyr.mod#545]
I'm loving the new feature for the menu items auto-hiding, however, I'm wondering if there's a setting for it that you could possible implement? As it is now, when you load the skin, the menu items will typically auto-hide while things are loading up. I'm wondering if you could add a setting for it in skin settings, so one could enable it only on-up (scrolling widgets) ? So I still want it to auto-hide the menu items, but only when I scroll up to the widgets, not when I load the skin. Hope that makes sense. Thank you.

**Comment by Nanomani** [comment]
If I all understand your request.
this already exist for "Vertical multi-widgets / Netflix" :)
I guess you use "Modern multi-widgets / Netflix" ? right ?

For "Vertical multi-widgets / Netflix" you must have this settings : 

![10](https://user-images.githubusercontent.com/3939543/134801720-57d1b257-3ee3-4f86-8d37-6cd531e2c877.jpg)

![20](https://user-images.githubusercontent.com/3939543/134801725-e9f7916e-f08b-4e1d-99d5-26dc432d0ca9.jpg)

**Comment by beatmasterRS** [comment]
@Nanomani i think he means, that the menu bar should only slide/hide, if widget container gets focused.

Maybe you could test https://github.com/beatmasterRS/skin.arctic.zephyr.mod/archive/refs/heads/home-hide-animation-patch-1.zip ?

**Comment by Nanomani** [comment]
> @Nanomani i think he means, that the menu bar should only slide/hide, if widget container gets focused.

I have do the same PR but not posted :) 

![1](https://user-images.githubusercontent.com/3939543/134812136-456f0b06-32e7-473f-b603-b18400712211.jpg)

**Comment by Nanomani** [comment]
@beatmasterRS sorry to bored you one more time. :)

I ask me if it will be not better to put for "vertical" ?
"On focus don't slide left" above  "Hide, when not focused/used"

with a new title :  
"On widget focus don't hide"

because "On focus don't slide left" is at the end of "widget" category in "home" skin settings

You see what I mean ?

**Comment by JC253** [comment]
> If I all understand your request.
> this already exist for "Vertical multi-widgets / Netflix" :)
> I guess you use "Modern multi-widgets / Netflix". right ?
> 
> For "Vertical multi-widgets / Netflix" you must have this settings :
> 
> ![10](https://user-images.githubusercontent.com/3939543/134801720-57d1b257-3ee3-4f86-8d37-6cd531e2c877.jpg)
> 
> ![20](https://user-images.githubusercontent.com/3939543/134801725-e9f7916e-f08b-4e1d-99d5-26dc432d0ca9.jpg)

Yes, I am using Modern Multi-Netflix. I've tried those settings before and it doesn't do what I'm trying to ask. Thank you though.

> @Nanomani i think he means, that the menu bar should only slide/hide, if widget container gets focused.
> 
> @JC253 Maybe you could test https://github.com/beatmasterRS/skin.arctic.zephyr.mod/archive/refs/heads/home-hide-animation-patch-1.zip ? (only for testing)

Yes, this is what I mean, thanks, I'll test it out today.

**Comment by JC253** [comment]
> @Nanomani i think he means, that the menu bar should only slide/hide, if widget container gets focused.
> 
> @JC253 Maybe you could test https://github.com/beatmasterRS/skin.arctic.zephyr.mod/archive/refs/heads/home-hide-animation-patch-1.zip ? (only for testing)

Yup, this was exactly what I was asking for. Thank you! Will this be merged into the master then? It'll be in the next update from the repo?

**Comment by beatmasterRS** [comment]
Yes, will be merged into master soon. Updates appear regularly in the repo, approximately every 3 weeks :)
