### ISSUE TITLE
[Request] Add "Only, when now playing is show"

### ISSUE THREAD

**Issue by Nanomani** [beatmasterRS/skin.arctic.zephyr.mod#560]
In same way "Only, when widget is focused"
add "Only, when now playing is show"

![1](https://user-images.githubusercontent.com/3939543/135843017-63655266-eedc-4525-8794-052c7bee3c49.jpg)

![2](https://user-images.githubusercontent.com/3939543/135845911-1f60fc24-6b60-467c-a282-7d6372c8d59c.png)

This mean that menu slide out if 
- widget is focused
- now playing is show

I hope my request is understandable ...

**Comment by beatmasterRS** [comment]
Good idea, but we need a simple condition/description for it...

**Comment by Nanomani** [comment]
You are right.

Perhap this will be better/more clear ?: 

disable :  
- "Only, when widget is focused"
- "Only, when now playing is show"

when 
- "Hide, when not focused/used" is disable like this :  

![1](https://user-images.githubusercontent.com/3939543/135872114-aabde5de-9a71-480f-ae6d-4868ed06d474.jpg)

![2](https://user-images.githubusercontent.com/3939543/135872324-a5a32b31-c5d2-43f5-93fd-30df78cfa29e.jpg)

then we can chose each situation where the menu is hidden.
?

**Comment by beatmasterRS** [comment]
Englisch (US) 
I meant: If I want to activate both options, then it is not very understandable, because both option names contain "only". In general, I would rather have as few options as possible. There are already countless options that are never used by the majority of users, I think...

But no pressure, we have time :)

**Comment by Nanomani** [comment]
Yes I understand that you mean. :)

Just delete the word "only, "
or 
Keep only one option for both: 

"Only, when widget is focused or when now playing is show"

**Comment by beatmasterRS** [comment]
I am looking for an other option labels then "Only, when widget is focused or when now playing is show". Just to be clear: the option will be added, just another label is needed, a short and clear label... :D
