### ISSUE TITLE
Hub Selection Issue

### ISSUE THREAD

**Issue by JC253** [beatmasterRS/skin.arctic.zephyr.mod#568]
Hello BeatMasterRS,
I've just come across an issue that I havent seen reported yet. I have 7 Hubs set up. The Hub Widgets all point to TMDbH items. When selecting a Movie from the Hub, you do get the TMDbH player dialog pop-up, but when selecting a TV Show from a Hub, nothing happens. Tried on all of my Hubs I have set up, same problem. Thanks.

**Comment by JC253** [comment]
> Please test this version:
> 
> https://github.com/beatmasterRS/skin.arctic.zephyr.mod/archive/refs/heads/hub-widgets-patch-1.zip
> 
> Now, the content type should be automatically set.
> 
> I hope, this works well for you

I'm getting a '404 NOT FOUND' when I click on that link to download it.

**Comment by beatmasterRS** [comment]
This branch has already been merged into master, so please test this version here please:

https://github.com/beatmasterRS/skin.arctic.zephyr.mod/archive/refs/heads/master.zip

**Comment by JC253** [comment]
Yup, that seems to work great, thanks!
