### ISSUE TITLE
Episode number & airdate on Netflix home like it is in views?

### ISSUE THREAD

**Issue by meesterexx** [beatmasterRS/skin.arctic.zephyr.mod#577]
Could we get the Season/Number/Airdate on the Netflix home for episodes how it is in the views? Right now it only shows year and it looks like there's plenty of room for it as seen in the pics below. 

Both my home and view are pulling from the same addon, and right now I have to turn on airdate/episode# for the title in the addon which makes for a loooonggg scrolling title on the homescreen and a corresponding wait to see all of that information.

Is it possible to add logic that essentially says if item type is episode then display the Season/Number/Airdate?

(btw, I did a font swap on Segoe-Light for Gotham-Light and did some minor tweaks to Font.xml, if the fonts are looking weird to you in the screenshots)

Homescreen:
![screenshot00000](https://user-images.githubusercontent.com/13154733/137357266-6ea21817-36e9-4290-8fdc-b0d4d34b5707.png)

Fanart Flix v2 Episodes:
![screenshot00001](https://user-images.githubusercontent.com/13154733/137357352-05ea41b2-2b7b-4ffa-bb0e-4674d4eeddbd.png)

**Comment by beatmasterRS** [comment]
Please have a look at this:

https://github.com/beatmasterRS/skin.arctic.zephyr.mod/archive/refs/heads/widgets-patch-4.zip

**Comment by beatmasterRS** [comment]
![screenshot00646](https://user-images.githubusercontent.com/3855273/137405370-79210124-605a-43db-bd5d-4a5eb684ae72.png)

**Comment by beatmasterRS** [comment]
Sure, just have a look at the liked PR, especially the files tab:

https://github.com/beatmasterRS/skin.arctic.zephyr.mod/pull/578/files

There you can see, all changes, i have made :)

**Comment by meesterexx** [comment]
Worked perfectly. Thank you very much, I'm not that good at github. I had only made 1 change in Includes_Home, so it was super quick to swap. :)

I think I may have found a bug, but you can tell me if it's by design. In the screenshots below, when I'm at the show level, unwatched episodes is 0, but when I'm at the season level it's 1 (which is correct, there's an episode airing tonight that I haven't watched yet). My UTC is -4, if that makes a difference.

Also, you can see the slight color changes I made by swapping in $VAR[ColorHighlight] for the colors of the title labels and the circle.png diffuse for unwatched episode count (when colored icons = true) as well as the slightly larger clear logos in the views.

Home:
![screenshot00004](https://user-images.githubusercontent.com/13154733/137493134-e504ab6c-c6ee-4b42-9cd7-97edc2bb8700.png)

Show:
![screenshot00001](https://user-images.githubusercontent.com/13154733/137493249-7512e8d2-649f-4461-8638-dbc5a9c28fea.png)

Info Dialog:
![screenshot00003](https://user-images.githubusercontent.com/13154733/137493484-9b2eecd7-1a43-4354-9a0c-78bdcda0597d.png)

Season:
![screenshot00002](https://user-images.githubusercontent.com/13154733/137493338-cb21224a-dd49-48df-8afa-991724e8ff06.png)

Episode:
![screenshot00005](https://user-images.githubusercontent.com/13154733/137493413-83c7c94e-966e-41fe-bdeb-7ec03aeb6f9e.png)
