### ISSUE TITLE
Movie release year in View_53_Poster ?

### ISSUE THREAD

**Issue by meesterexx** [beatmasterRS/skin.arctic.zephyr.mod#584]
Big Poster (View_53_Poster) has airdate for TV Shows, but no release year for movies. Would it be possible to get one added offically to the view somewhere?

I added one to colored icons for movies in the same spot as airdate for shows, but it would be nice to have it officially in the skin, and you may have a better idea on implementing it more elegantly.

![screenshot00001](https://user-images.githubusercontent.com/13154733/137806077-54e55ff3-cecd-4072-bdb5-2a3b6517cdf0.png)

I did a quick and dirty hack right before the mpaa rating in Includes_Furniture where Skin.HasSetting(furniture.coloredicons):
            `<control type="image" description="Year">
                <width>52</width>
                <height>64</height>
                <centertop>50%</centertop>
				<texture colordiffuse="$VAR[ColorHighlight]">DefaultYear.png</texture>
                <aspectratio align="left">scale</aspectratio>
                <visible>String.IsEqual(Container($PARAM[id]).ListItem.DBType,movie)</visible>
            </control>`

`            <control type="label" description="Year">
                <width>auto</width>
                <centertop>50%</centertop>
                <height>64</height>
                <align>left</align>
                <aligny>center</aligny>
                <label>$INFO[ListItem.Year]  </label>
                <font>Flag</font>
                <textcolor>Dark1</textcolor>
                <visible>String.IsEqual(Container($PARAM[id]).ListItem.DBType,movie)</visible>
            </control>`

**Comment by beatmasterRS** [comment]
Unfortunately not, because I try to keep the skin lightweight and only add things that are e.g. relevant to all views.
