### ISSUE TITLE
Games Library

### ISSUE THREAD

**Issue by IanWONeill** [beatmasterRS/skin.arctic.zephyr.mod#6]
Are you able to port the games library to this build as done with the K17 version by @KODser on the Kodi Forums?

https://imgur.com/a/lSGU9

See more info here:
https://forum.kodi.tv/showthread.php?tid=307462&pid=2529541#pid2529541

IMO this would be a perfect fitting for builds on XBOX ONE for when a (non-developer mode) situation occurs with Retro Emulation.

**Comment by beatmasterRS** [comment]
Its done :)
