### ISSUE TITLE
Power off

### ISSUE THREAD

**Issue by Thomaskito** [beatmasterRS/skin.arctic.zephyr.mod#628]
When i use this skin and power off the box is regular freeze and don't power off.
Don't have this with others skin.
U have a minix u22 with coreelec kodi 19.3

**Comment by beatmasterRS** [comment]
What other skins have you tested?

- Please enable "Enable debug logging" in > Settings > System > Logging. 
- After that, open the power menu and hit "Shutdown" to shutdown coreelec.
- Try to establish a remote connection and provide the kodi.log or the kodi.old.log file

Maybe i can see something in the log file.

Thank you

**Comment by Thomaskito** [comment]
Now i use aeron nox silvo.
I Will try to make the log file and upload it.


Outlook voor Android<https://aka.ms/AAb9ysg> downloaden
________________________________

**Comment by beatmasterRS** [comment]
If there are any news, feel free, to reopen this issue.
