### ISSUE TITLE
support for PVR artwork

### ISSUE THREAD

**Issue by kalle2000** [beatmasterRS/skin.arctic.zephyr.mod#637]
Dear @beatmasterRS,

would it be possible to support PVR artwork for your skin?
in Include_Images.xml I managed to show posters for pvr channels already (with your help):

`<value condition="!String.IsEmpty(ListItem.EpgEventIcon) + String.StartsWith(ListItem.FolderPath,pvr://)">$INFO[ListItem.EpgEventIcon]</value>`

In another [thread](https://forum.kodi.tv/showthread.php?tid=359645) I read that replacing _$INFO[ListItem.EpgEventIcon]_ by _$INFO[Pvr.EpgEventIcon]_ is supposed to show PVR artwork. Apparently I do not get it to work with your skin.

`<value condition="!String.IsEmpty(ListItem.EpgEventIcon) + String.StartsWith(ListItem.FolderPath,pvr://)">$INFO[Pvr.EpgEventIcon]</value>`

**Comment by beatmasterRS** [comment]
Where exactly would you like to see PVR artwork?

**Comment by beatmasterRS** [comment]
Screenshots could be helpful

**Comment by kalle2000** [comment]
I am using Home menu style "Modern Multi-widgets Netflix" and when I customize the home menu and adding widgets for movies or tvshows, I can select various widgets aspects such as "Small poster thumbnail" or "fanart".

[Home menu](https://ibb.co/c2fN4CW)

For PVR this does not work (widget: Last Played Channels) as only the channel icon is shown. With the tweak from my first post at least the poster is shown.

[PVR home menu](https://ibb.co/7rpGm8c)

So my question is if it is possible to support the same widgets aspects for PVR as for movies/shows.

The PVR artwork itself is fetched via [Skin Helper service](https://github.com/kodi-community-addons/script.skin.helper.service/wiki/Listitem-Properties---Artwork)

**Comment by kalle2000** [comment]
It seems that a new module is in the works to support PVR artwork: 
[Kodinerds Thread](https://www.kodinerds.net/index.php/Thread/74297-Estuary-MOD-V2-Matrix-PVR-Sektion/?pageNo=1)
