### ISSUE TITLE
Cannot install.

### ISSUE THREAD

**Issue by SirRickie** [beatmasterRS/skin.arctic.zephyr.mod#64]
Wanted to try your skin, but when installing, it gives me the error "dependency on xbmc.gui 5.15.0 could not be satisfied". Is there something I can do to make it run ? I'm on WN10, Kodi 18.9.

**Comment by beatmasterRS** [comment]
Please select the leia branch, before download, or use this link, to get always the latest leia version:

https://github.com/beatmasterRS/skin.arctic.zephyr.mod/archive/leia.zip

![Image16](https://user-images.githubusercontent.com/3855273/106747582-64260080-6624-11eb-9c0f-b27776cb23cd.jpg)

**Comment by SirRickie** [comment]
Got it. Tnx. Tested it for a while. Looks really nice. One downside : no mouse support. Have to get used to it. 😥
