### ISSUE TITLE
Tv show Widget not backing out to the home screen

### ISSUE THREAD

**Issue by deyooluv** [beatmasterRS/skin.arctic.zephyr.mod#650]
How to replicate issue
1. Set kodi default action to show information
2. Using any add-on then set widget to any category of the tv show to the home screen.
3. On the home screen, click a tv show then click browse and then click episode to play(PS: playing an episode is not necessary to replicate this issue). Watch out for the small box on the left of the screen.
4. Press back to go back to the home screen
5. The behavior seen here shows that instead of the back button to take you to the home screen it instead goes through the add-on the widget was pointed.
6. This behaviour is only happening to tv shows widget in the home screen.

**Comment by beatmasterRS** [comment]
That seems to be a Kodi issue. There is already an open PR, fix thix behavior:

https://github.com/beatmasterRS/skin.arctic.zephyr.mod/pull/615

**Comment by deyooluv** [comment]
> That seems to be a Kodi issue. There is already an open PR, fix thix behavior:
> 
> #615

Has the fix been merged to the lastest update?
Other skin that I have tried don't have this behaviour. Thank you

**Comment by beatmasterRS** [comment]
> Has the fix been merged to the lastest update? 

No

> Other skin that I have tried don't have this behaviour. Thank you

Please take a look: https://forum.kodi.tv/showthread.php?tid=345847&pid=3072974#pid3072974

**Comment by deyooluv** [comment]
> > Has the fix been merged to the lastest update?
> 
> No
> 
> > Other skin that I have tried don't have this behaviour. Thank you
> 
> Please take a look: https://forum.kodi.tv/showthread.php?tid=345847&pid=3072974#pid3072974

Hopefully you can fix it. Thank you

**Comment by beatmasterRS** [comment]
Just tested it with Estuary, even there the behavior is the same. We will see.
