### ISSUE TITLE
Provider icons need attribution to JustWatch

### ISSUE THREAD

**Issue by jurialmunkey** [beatmasterRS/skin.arctic.zephyr.mod#671]
Hi there. I noticed that you're using the provider icon details from TMDbHelper. 

I've recently found out that it is necessary to attribute JustWatch directly for this data whenever it is used. That means that you must provide attribution on the same screen as the information is displayed.

I've updated the TMDbHelper wiki to include this info (and also Arctic Horizon to provide this attribution).
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/wiki/Service-Monitor#watched-providers

If you could also update your skin to provide this attribution whenever you use this data, that'd be much appreciated so that my api key doesn't get disabled. Here's a logo that I made for AH to use (Though you can make your own if you prefer - the rule is that it must show the JustWatch logo and make it clear that the data comes from JustWatch).

![](https://camo.githubusercontent.com/bbdcf81b445e322ce70bfb8c6855b2137a5ab0bde4662742d67ec66d6d4a3ee2/68747470733a2f2f692e696d6775722e636f6d2f4f5264723234502e706e67)

**Comment by beatmasterRS** [comment]
Thank you for informing me about this. I have just changed it:

![screenshot00920](https://user-images.githubusercontent.com/3855273/147463574-6571bae4-5f42-47c5-aa54-8b674380b1c9.png)

**Comment by jurialmunkey** [comment]
Perfect! Thanks so much for the quick change/update.
