### ISSUE TITLE
Jellyfin icon ready to use

### ISSUE THREAD

**Issue by martinbiard** [beatmasterRS/skin.arctic.zephyr.mod#676]
I created a [Jellyfin](https://jellyfin.org) icon that can go into `skin.arctic.zephyr.mod/extras/icons`, sorry not much time to create a pull request but I'll leave it here as attachment.

![jellyfin](https://user-images.githubusercontent.com/5204353/147619241-4d315184-d849-4e8e-8421-b6a12a03b5f1.png)

**Comment by beatmasterRS** [comment]
Could you please provide a png, where the visible icon is 64x64?

**Comment by martinbiard** [comment]
I ended up creating a Pull Request https://github.com/beatmasterRS/skin.arctic.zephyr.mod/pull/679, and made the visible icons 64x64, then padded to 128x128.
