### ISSUE TITLE
Japanese font support

### ISSUE THREAD

**Issue by aanderse** [beatmasterRS/skin.arctic.zephyr.mod#7]
Prior to upgrading to Kodi 18 I was using Artic Zephyr which had support for Japanese fonts. When I upgraded to Kodi 18 I noticed Artic Zephyr wasn't available so I installed your plugin but found there was no font which supported Japanese text. I'm not sure if this is a Kodi 17 -> 18 issue, or a regression with this skin.

**Comment by beatmasterRS** [comment]
Will be fixed within the next update :)

**Comment by aanderse** [comment]
Great thanks!
