### ISSUE TITLE
HW and SW Decoding under Player Preogress Info

### ISSUE THREAD

**Issue by TBSemiotikLE** [beatmasterRS/skin.arctic.zephyr.mod#715]
Hi, 
![IMG_20220123_035455](https://user-images.githubusercontent.com/85806745/150659551-17de9f15-a575-4788-9a35-e55a93365a99.jpg)
![IMG_20220123_035541](https://user-images.githubusercontent.com/85806745/150659558-1bf7e7d4-d064-4834-a526-0abe42082966.jpg)

can you add in the Player Progress Info HW und SW Decoder under Video and Video Decoder? (is missing in your skin)

**Comment by beatmasterRS** [comment]
Has been added: https://github.com/beatmasterRS/skin.arctic.zephyr.mod/commit/5ecd91b02e6bea925af2ebe54a71b2a3b244b38d
