### ISSUE TITLE
RFE: hide watched (option) in spotlight

### ISSUE THREAD

**Issue by bugsyb** [beatmasterRS/skin.arctic.zephyr.mod#717]
Would be great to be able to hide watched movies/shows in spotlight/main hub view, same as at other levels. 

Thank you!

p.s. for the life of me, couldn't find it in settings - maybe am just blind.

**Comment by beatmasterRS** [comment]
Thats not possible, sorry.

**Comment by bugsyb** [comment]
It's pity, as flags "watched" are possible and generally other skins, even basic one allows to hide watches items.
Motivation is that on the system where majority of items are watched the spotlight/main view becomes useless as is busy with almost all "watched" items.

**Comment by beatmasterRS** [comment]
Sorry, but what exactly are you talking about? In the first post, you mentioned "spotlight/main hub view" There is a significant difference between the home viewtype "spotlight" and a "hub". If you say "even basic one allows to hide watches items", what skins do you mean?

If you are talking about the main menu and the widgets, you should perhaps take a look at the widget-configuration in skin settings > customize home menu. There you can select exactly what should be shown. For example, "new unwatched movies".

> Thats not possible, sorry.

What i meant with that is, that if you have a basic list, e.g. movies > titles, there is no way to filter that.

**Comment by beatmasterRS** [comment]
I am closing this issue now. If you have any further questions, feel free to comment below.

**Comment by bugsyb** [comment]
> If you are talking about the main menu and the widgets, you should perhaps take a look at the widget-configuration in skin settings > customize home menu. There you can select exactly what should be shown. For example, "new unwatched movies".
> 
> > Thats not possible, sorry.

Skin customization allows to put "labels" like "new", "watched" but doesn't allow these to be filtered on main screen - or I didn't find a way. It shows all items anyway always. This makes the view busy, but also more or less useless in case of larger library as is close to impossible to fish out unwatched items.

Would be great is such option could be added and understood that it doesn't exist - hence the title request for enchancement (RFE).

Thank you!

p.s. unfortunately I'm not able to add functionality myself.
