### ISSUE TITLE
Background Issuie (Resulotion)

### ISSUE THREAD

**Issue by TBSemiotikLE** [beatmasterRS/skin.arctic.zephyr.mod#718]
Hello, 

i think somewhere in the settings is for the Background a small Resulotion because on small Displqy with a small Resulotion i have the Backgrounds normal  .. 

as example 
1366 x 768 (there is all OK) 

if i used 
1920x1080 (the Background repeat to the left side and overlaps) 

please fix this with the standard resulation from 1920x1080 or higher and the system resize 1x1 the background) 

if you need Photos , iin can upload! 

Regards

**Comment by beatmasterRS** [comment]
Why not attach screenshots with this topic?

**Comment by TBSemiotikLE** [comment]
![screenshot00011](https://user-images.githubusercontent.com/85806745/151161132-65d69872-5111-410f-b07d-018f19034db0.png)
![screenshot00000](https://user-images.githubusercontent.com/85806745/151161157-ada783e8-07af-48a6-9712-7cccdcb17182.png)

small vs full hd resulotion 

Here youbsee good what i mean

**Comment by beatmasterRS** [comment]
What you see, is the global fullscreen background and top right the netflix fanart window. You can use the follwing settings to adjust that to your needs:

>>skin settings > home > netflix fanart window
>>skin settings > home >      fullsize fanart
>>skin settings > home >      brightness
>>skin settings > background > brightness

**Comment by beatmasterRS** [comment]
I am closing this issue now. If you have any further questions, feel free to comment below.
