### ISSUE TITLE
Please add Settings for AudioProfile

### ISSUE THREAD

**Issue by TBSemiotikLE** [beatmasterRS/skin.arctic.zephyr.mod#719]
Hello, 
its possible please add in the future under 

settings - skin settings - furniture 
AudioProfile for the Player  OSD

Addon
https://kodi.wiki/view/Add-on:Audio_Profiles

in the Kodi Forum (Example 3)
https://forum.kodi.tv/showthread.php?tid=200081

Regards

**Comment by beatmasterRS** [comment]
I won't add this as I don't use the addon and think that compared to the effort to add it, not many users use it, sorry.
