### ISSUE TITLE
PlexKodiconnect TrailerAutoplay integration issue

### ISSUE THREAD

**Issue by xenophobentx** [beatmasterRS/skin.arctic.zephyr.mod#724]
When you are syncing your library with plexkodiconnect https://github.com/croneter/PlexKodiConnect the listitem trailer property is preloaded with the following value if trailer found by plex for the item: plugin://plugin.video.plexkodiconnect.movies/?mode=play&plex_id=16961&plex_type=clip

Autoplay is triggered and the trailer is played in full screen instead of  background.
![trailerplex](https://user-images.githubusercontent.com/31575788/151656062-51bb98f5-5d1d-4512-9465-0a52f22b95b9.jpg)

Is it possible to have this integrated shomehow? Or to override to use kodi trailer provider instead of plexkodiconnect?

**Comment by beatmasterRS** [comment]
I think I had read something in the Kodi forum about this, that this concerns a setting in Plex, but unfortunately I don't remember exactly. There was a user who had the same problem.

**Comment by xenophobentx** [comment]
Thans for the quick response. Well only workaround that i know is to disable trailer collection in plex but that way i lose access to trailers in other( not kodi clients) will ask the forum and come back if got any update.

**Comment by xenophobentx** [comment]
Ok it seems that i open this one in the leia version bot in the martix one. Sorry for that.

**Comment by xenophobentx** [comment]
Created kind of a hack for plexkodiconnect to prefer local trailers for such functionality:
https://github.com/croneter/PlexKodiConnect/issues/1783

**Comment by beatmasterRS** [comment]
Thanks for clarifying. so this issue can be closed?

**Comment by xenophobentx** [comment]
Well kind of interesting why plexkodiconnect url resulting in a popup and fullscreen play but youtube not. Not sure about the real cause here but workaround give as some benefits with local language trailers. I would say you can close it.
