### ISSUE TITLE
FR: Widget label renaming

### ISSUE THREAD

**Issue by thorindwarf** [beatmasterRS/skin.arctic.zephyr.mod#779]
Hey! :)

Can we have an option for changing the label of a widget without going through the whole process of choosing a widget and after that entering/modifying its name?

Thanks!
Tried a lot of skins and this is my favorite despite the slower start/reload especially on a slow cpu device like CCWGTV.

**Comment by beatmasterRS** [comment]
I already tried that, but unfortunately it is not possible due to the way it is implemented, sorry...

>>Tried a lot of skins and this is my favorite despite the slower start/reload especially on a slow cpu device like CCWGTV.

With the next version, the skin will be noticeably faster. :)
