### ISSUE TITLE
[inquiry/feature request] Audio/subtitle language info

### ISSUE THREAD

**Issue by Sopel97** [beatmasterRS/skin.arctic.zephyr.mod#792]
Hey, I really like this skin because it provides the most (from the skins I tested) information about the movie entries in the main screen. (Just to be clear, I'm talking about this place 
![obraz](https://user-images.githubusercontent.com/8037982/156791540-906eacdf-e864-498c-94fe-3ba926a64373.png)) However, I have a specific need regarding this display. I'd like to have audio and subtitle availability information for (2) selected languages. I'd appreciate even some pointers as to where to start looking in the codebase to implement custom info entries. Thanks.

**Comment by beatmasterRS** [comment]
Please take a look in skin settings > furniture:

![screenshot01138](https://user-images.githubusercontent.com/3855273/156797937-19c13de7-1191-4d80-9840-4ae058709bc1.png)

and enable 

>subtitle icon > subtitle extended info
>audio streams

with that, you will get:

![screenshot01139](https://user-images.githubusercontent.com/3855273/156798149-ae41261e-3cc6-4db3-9902-83d7b78a95ab.png)

If you have any further questions, please let me know.

**Comment by Sopel97** [comment]
Thanks, completely missed this one. Solves the issue.
