### ISSUE TITLE
Video OSD auto close and watched indicators in widgets no longer work

### ISSUE THREAD

**Issue by PSTrophy** [beatmasterRS/skin.arctic.zephyr.mod#80]
In the latest master the video OSD auto close no longer works and the green watched indicators in widgets no longer work but when I go into the widgets location they show in the add-on so they are enabled. The add-ons are S_r_n and O_th if that helps. Tmdb helper widgets work fine.

**Comment by beatmasterRS** [comment]
Sorry, i don't support banned addons.

**Comment by PSTrophy** [comment]
What do you mean banned they are freely available. Just because you don't support them or use them plenty do. But you do you. Appreciate the hard work on the skin though :)

**Comment by fabricionaweb** [comment]
`what do you mean` I think is this https://kodi.wiki/view/Official:Forum_rules/Banned_add-ons
