### ISSUE TITLE
Additional Context Menu Support

### ISSUE THREAD

**Issue by fynflood** [beatmasterRS/skin.arctic.zephyr.mod#803]
Really loving this Skin, but missing the ability to start CinemaVision (https://cinemavision.tv/). 

https://cinemavision.tv/guides/cinemavision-kodi-add-ons/skin-integration-developer-information/

**Comment by beatmasterRS** [comment]
There is mostly only support for add-ons, that are in the official repo. In addition, there is no stable release of the cinema addon yet, only a developement version. For cinema feeling, this skin uses the cinema mode of embuary helper script:

https://github.com/sualfred/script.embuary.helper/wiki/Script:-Cinema-mode#information
