### ISSUE TITLE
Hide "HomeNextRecording" if "more clean & minimal" is selected

### ISSUE THREAD

**Issue by kalle2000** [beatmasterRS/skin.arctic.zephyr.mod#810]
.... in order to be more clean & minimal :)

**Comment by beatmasterRS** [comment]
What do you mean exactly? Please describe the issue in more detail, thank you.

**Comment by kalle2000** [comment]
[Homescreen](https://ibb.co/0289LsC)

I am using TVHeadend as backend. And in "PVR service" settings I have deactivated any kind of notification (e.g. Recording --> Display a notification on timerr updates).
In case no recordings is running, that window is showing the next upcoming recording. Hence is visible all the time.

**Comment by beatmasterRS** [comment]
Okay, now I understand what you mean. Well, since this is a dialog with information, it's not good to hide it by setting "more clean & minimal". But I could imagine an option in the PVR area where you can disable the info dialogs "current recording" and "upcoming recording".

**Comment by Morphy99** [comment]
Came here looking to suggest exactly this. I constantly have a "Next recording..." info dialogue on my home screen which I'm not interested in. Currently recording is however, useful.

**Comment by beatmasterRS** [comment]
I will take a look at this soon, before the next update :)

**Comment by beatmasterRS** [comment]
@kalle2000 @Morphy99 

I just looked at this and will add this option. But I do not really know where to put this option? 

Skin Settings > 
> Home? 
> Extras?
> Furniture?

What do you think?

![screenshot01278](https://user-images.githubusercontent.com/3855273/193106228-42f0cd6e-7cf2-4669-bec2-7d6bb90075ca.png)

**Comment by kalle2000** [comment]
As the info is shown on the Home screen, putting the option into "Home" makes sense to me. Maybe you want to rename it to "Show PVR recording dialogue" instead

**Comment by Morphy99** [comment]
Home would make sense for me too. 
I've noticed another PVR related issue, on radio now playing the channel number is not displayed anywhere. Do you want me to submit a new issue?

**Comment by beatmasterRS** [comment]
Thanks for all your feedback.

@Morphy99 yes please open a new issue, with screenshots please.
