### ISSUE TITLE
Plot and Fanart issue

### ISSUE THREAD

**Issue by lm209** [beatmasterRS/skin.arctic.zephyr.mod#828]
is it possible to shrink the fanart from the widget?  so that the plot doesn't become illegible in the fanart because it overlaps.

**Comment by beatmasterRS** [comment]
Could you provide a screenshot of what you mean exactly?

**Comment by lm209** [comment]
![image~2](https://user-images.githubusercontent.com/82281970/174145295-b0d5f889-54ef-4f13-b173-bd8a86e29453.png)
with my setting, the fanart is displayed completely, there is a possibility to display a black background on the plot and the fanart next to it. Its only a example picture from another skin.

**Comment by beatmasterRS** [comment]
In skin settings you could try to enable fullscreen fanart for netflix window and increase brightness of it. After that, reduce the brightness of the background in background settings.

**Comment by beatmasterRS** [comment]
Thanks a lot, then I can close this issue.
