### ISSUE TITLE
Autoscrolling widget plot feature

### ISSUE THREAD

**Issue by ArtyIF** [beatmasterRS/skin.arctic.zephyr.mod#844]
Hello, I'm currently translating this skin to Russian, and I noticed that there was a string of "Autoscrolling widget plot". I was searching for that option yesterday and couldn't find it. But when I looked up the context number on GitHub, only the .po files came up. Was this feature removed or is it planned?

**Comment by beatmasterRS** [comment]
Thanks for your translations! The "Autoscrolling widget plot" string is not used anymore. Instead the string Id 20189 from the Kodi language files is used in control 9850 in furniture section in skin settings.

If you enable debugging, you can see the current focused control Id in the top left. That could help to find the controls/strings. If you have any further questions, please let me know :)

**Comment by ArtyIF** [comment]
Furniture section? I don't think I have that.

**Comment by beatmasterRS** [comment]
Please have a look here:

![screenshot01233](https://user-images.githubusercontent.com/3855273/186920292-c2e77afe-5b36-46d9-bf5d-9c4d944403e3.png)

**Comment by ArtyIF** [comment]
Okay, found it. It's called "Elements" in Russian, which TBH makes a lot more sense than "Furniture".
