### ISSUE TITLE
Artist text in music OSD sometimes ellipsizes and doesn't scroll

### ISSUE THREAD

**Issue by ArtyIF** [beatmasterRS/skin.arctic.zephyr.mod#847]
In some cases, the repeating artist name in music OSD doesn't scroll and ellipsizes at the end. Example: (apologies for terrible picture quality)

![IMG_20220903_114157](https://user-images.githubusercontent.com/8017858/188263593-eab7b5dc-068c-401c-835e-bc852aa80b18.jpg)

**Comment by beatmasterRS** [comment]
This is a known problem and there is nothing you can do from the skin side. When you play a long title, scrolling stops after a few minutes and there is no way to start scrolling again.

**Comment by ArtyIF** [comment]
I don't know how skins work, but is it possible to fill the artist text enough to make a scrolling looping animation of sorts?

**Comment by beatmasterRS** [comment]
I have done some tests with it and it doesn't work.
