### ISSUE TITLE
Mute Icon Appears in Upper Left

### ISSUE THREAD

**Issue by Refugee-Allstar** [beatmasterRS/skin.arctic.zephyr.mod#85]
This bug is quite strange. Each time I load the skin the mute icon appears in the upper left of the screen. It persists during video plays -- despite the sound working properly. The only way to remove it is to reload the skin from the power menu. 
![Uploading PXL_20210225_235400209.MP.jpg…]()

**Comment by beatmasterRS** [comment]
Does this also happen on other Skins?

**Comment by beatmasterRS** [comment]
Could you provide screenshots of that behaviour?

**Comment by Refugee-Allstar** [comment]
> Does this also happen on other Skins?

This does not happen on other skins -- but I have only tested one other skin. Here are some screenshots and videos showing the bug in more detail:

https://ibb.co/yYq9pc8
https://ibb.co/N6bf951
https://ibb.co/BtWdLfw

Here are some videos showing the bug fixing itself upon reloading the skin and showing the sound playing correctly.

 https://youtu.be/HBpn-fTUZss -- appears on fresh Launch

 https://youtu.be/pmpVrfJtvjk - fixes upon skin reload

 https://youtu.be/Bf3i2Tof4qY - persisting during video play and the sound playing normally

**Comment by beatmasterRS** [comment]
Here you can see the respective lines of code: https://github.com/beatmasterRS/skin.arctic.zephyr.mod/blob/306df67a185b0ac6bc4237d0a2af5b045f31dabb/1080i/DialogVolumeBar.xml#L183-L238
Line 184 starts with `<visible>Player.Muted</visible>` so this group and its textures are only visible, when player is muted.
https://kodi.wiki/view/List_of_boolean_conditions#Player -> "Player.Muted" -> "Returns true if the volume is muted."

So this is not a skin issue.

**Comment by Refugee-Allstar** [comment]
Thank you for this. I am going close this issue. I figured out the problem. I originally set the skin up on my PC which was muted at the time. I then copied the build over to a different device. By default the "mute" setting was on until I reloaded the skin, which removed it since that device wasn't muted.
