### ISSUE TITLE
PVR Now Playing Improvements

### ISSUE THREAD

**Issue by Morphy99** [beatmasterRS/skin.arctic.zephyr.mod#862]
PVR Now Playing could do with an overhaul IMHO. It would be helpful if this dialogue showed the Channel name, Program Info, Channel Logo, as well as the existing start and end time. Also, the Channels, Now/Next and Timeline buttons are all (unnecessarily?) cropped. Maybe the should be changed to icons if space is an issue?
![screenshot00000](https://user-images.githubusercontent.com/5853979/193263162-084ab8b5-a1f8-4cd0-8e2a-1eb842bc2605.png)

Some examples are the standard Estuary which shows the info at the top:
![screenshot00004](https://user-images.githubusercontent.com/5853979/193264326-4433ef29-8862-41ee-80f7-a16c9f1628c5.png)

Bello on my LE 9 system has the correct amount of info imho:
![screenshot000](https://user-images.githubusercontent.com/5853979/193264543-12b9e861-61ce-4b4a-8923-bbbb042190e2.jpg)

There also exists the posibility of going full on with Artwork provides like the Estuary PVR+ Skin:
https://imgur.com/17toMOW

**Comment by beatmasterRS** [comment]
Thanks for your feedback. As many other skins, this one has it's own design language and functions.

The skin differentiates between 

>> the OSD dialog (m), i.e. the osd buttons and
>> the information dialog (i)

If you show both dialogs, the lower labels will be cut off. 

![screenshot01281](https://user-images.githubusercontent.com/3855273/193281190-ee9bedfd-6b13-42e2-8642-3877b500619b.png)

There is no final solution for this yet.

**Comment by Morphy99** [comment]
Did you make any changes or is this a "won't fix"?
