### ISSUE TITLE
Duplicated lines in translation pl

### ISSUE THREAD

**Issue by AdiOpi** [beatmasterRS/skin.arctic.zephyr.mod#869]
Duplicated lines in translation pl

msgctxt "#31149"
msgid "Replace widget fanart with background"

#~ msgctxt "#31149"
#~ msgid "Replace widget fanart with home background slideshow"

**Comment by beatmasterRS** [comment]
Translations are handled by weblate, kodis translation system. Lines are commented out, so there is nothing to do, all is fine :)
