### ISSUE TITLE
Logo and Text misalignment on Seren's Scraping and Resolving window 

### ISSUE THREAD

**Issue by Nuklear92** [beatmasterRS/skin.arctic.zephyr.mod#88]
Greetings, perhaps this is something not related to your end of the skin and mostly on Seren's side of things. I'll leave it anyways in case you wanna check it out, or perhaps you might had noticed it by now if you're familiar with this Add-on. When scraping starts there's seems to be an issue with the logo and font being on top of each other, this is present on both scraping and resolving link windows. For reference I'll also post screenshots of how it looks on Arctic Horizon skin. Hence, Seren's Dev actually has personally tested these skins on his end when Seren 2.0 was released, so i'm definitely guessing in the end this will have to be fixed from Seren's side.

### Here's how it looks on Arctic Zephyr Reloaded:
![47CF7057-3E38-4E86-9529-55958A715375_1_105_c](https://user-images.githubusercontent.com/76958541/109315125-304f8c80-7818-11eb-9887-f0b3461d9837.jpeg)
 ![CFB70DA1-D52A-4950-BB16-988BCE22A09C_1_105_c](https://user-images.githubusercontent.com/76958541/109315174-3e051200-7818-11eb-835c-6f463cd5a63b.jpeg)

### Here's how it should look, this is on A.H but also looks the same way on Estuary, Aura, Aura Mod, Arctic Zephyr 2, AZ2Mod, etc.
![3AD6D799-C687-4A60-B370-99726598C896_1_105_c](https://user-images.githubusercontent.com/76958541/109315483-9805d780-7818-11eb-9ae2-6973afc4792f.jpeg)
![Kodi_20210226_092355](https://user-images.githubusercontent.com/76958541/109315741-d8655580-7818-11eb-9ffb-16611fb4632f.png)

**Comment by beatmasterRS** [comment]
Sorry, i don't support banned addons!
