### ISSUE TITLE
Metacritics and Rotten Tomatoes ratings in lists

### ISSUE THREAD

**Issue by shumafuk** [beatmasterRS/skin.arctic.zephyr.mod#898]
Is it possible to show metacritics or rotten tomatoes (ideally both) ratings in library lists? Thanks.

**Comment by beatmasterRS** [comment]
Do you mean in the footer along the other media flags?

**Comment by shumafuk** [comment]
Yes. There is one rating, but I guess it's from IMDB. Metacritics and Rotten Tomatoes are more relevant for me.

**Comment by beatmasterRS** [comment]
In skin settings > furniture > select media flags, please enable "rottentomatoes & metacritic"

**Comment by shumafuk** [comment]
Oh, great! I didn't know that. Unfortunately rating in lists shows "...", but I hope it need some time to download data.

**Comment by beatmasterRS** [comment]
What rating, especially in lists do you mean? the rating in the list itself?

**Comment by shumafuk** [comment]
Where exactly rating from Metacritics and Rotten Tomatoes should be? I set this option ON, but rating that is showed here is same a default (TMDB).

![2023-01-15](https://user-images.githubusercontent.com/62727484/212501011-9f2d4a61-44cb-4a4e-8325-d22477b63553.png)

**Comment by beatmasterRS** [comment]
The should be shown at the bottom:

![screenshot01309](https://user-images.githubusercontent.com/3855273/212501297-ef265352-ac89-4f76-a5fe-2872fa106e01.png)

**Comment by beatmasterRS** [comment]
Dont forget to set an omdb key in the tmdb helper addon settings.

**Comment by shumafuk** [comment]
After adding API key ratings appear only on few titles.

**Comment by beatmasterRS** [comment]
Then, all is fine from the skin side.

**Comment by shumafuk** [comment]
Yes, it shows in 95% of films after also putting MDbList API key. Thanks.
