### ISSUE TITLE
Video calibration not working on Kodi 20.0

### ISSUE THREAD

**Issue by eevlogiev** [beatmasterRS/skin.arctic.zephyr.mod#907]
### Describe the bug
Running Kodi 20 Nexus on a Sony Android TV skin Arctic Zephyr - Reloaded, I wanted to change subtitles position, when I go to Settings-System-Display-Video Calibration and try to adjust any border using my remote control arrow keys - nothing happens. However when I tried using an external wireless keyboard I was able to adjust lines using my keyboard mousepad. Also I tried with Estuary skin and remote controls are working.

## Expected Behavior
I should be able to adjust screen borders when in Video calibration mode using my TV remote control.

## Actual Behavior
Nothing happens, I just hear regular Kodi clicking sound when I am pressing the arrow keys on the remote control.

### To Reproduce
On Android TV, go to Settings-System-Display-Video Calibration and try to adjust any line using your TV remote control

### Your Environment
Used Operating system:
 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android TV 9.0.0
 - Kodi version: 20.0
 - Skin: Arctic Zephyr - Reloaded

Debug log: [kodi.log](https://github.com/beatmasterRS/skin.arctic.zephyr.mod/files/10529666/kodi.log)

**Comment by beatmasterRS** [comment]
Thanks for reporting. Should be fixed now.
