### ISSUE TITLE
Don't get IMDB rating

### ISSUE THREAD

**Issue by mkaflowski** [beatmasterRS/skin.arctic.zephyr.mod#909]
I dont get IMDB or TMDB ratings:
![Zrzut ekranu 2023-01-30 o 15 19 44](https://user-images.githubusercontent.com/10148175/215502716-44a33a31-0584-457f-901b-c37ac0fbbabf.jpg)

Do I need to activate it somewhere? When I change skin to Zephyr 2 it works.

**Comment by beatmasterRS** [comment]
Please have a look in skin settings > furniture > select media flags > IMDB Top 250

**Comment by beatmasterRS** [comment]
Then there is nothing i can do from the skin side. The skin only uses the ListItem.Top250 infolabel. If the label is empty, no icon is shown.

**Comment by mkaflowski** [comment]
Will try to add it.

pon., 30 sty 2023, 19:24 użytkownik beatmasterRS ***@***.***>
napisał:

**Comment by mkaflowski** [comment]
https://github.com/beatmasterRS/skin.arctic.zephyr.mod/pull/911
