### ISSUE TITLE
Missing movie tag lines

### ISSUE THREAD

**Issue by mkaflowski** [beatmasterRS/skin.arctic.zephyr.mod#910]
It would be great to see tag lines for movies for example as a bolded beginning of description like that (it is my Zephyr 2 modified):

![image](https://user-images.githubusercontent.com/10148175/215504051-d25246b1-5fd9-4fa4-9e39-8818690ea964.png)

**Comment by beatmasterRS** [comment]
Tagline is only available in the dialog video info. 

![screenshot01323](https://user-images.githubusercontent.com/3855273/215563978-bb3fd74b-54fa-4eee-b2ef-b068fba9c881.png)

It's not planned to show the tagline in the video views.
