### ISSUE TITLE
UTF-8 not supported

### ISSUE THREAD

**Issue by toxygen** [beatmasterRS/skin.arctic.zephyr.mod#93]
The font that is used in the skin does not support letters like ľ, ť, č, etc.

**Comment by fabricionaweb** [comment]
Have you tested other fonts? You can choose between 5, do you know if happens to all of them?

![image](https://user-images.githubusercontent.com/15933/109384801-3eb8a980-78e7-11eb-85ac-de572f913340.png)

**Comment by toxygen** [comment]
Failback works fine. The default one does not. Do not know about others, will try tomorrow when I’m back home.
