### ISSUE TITLE
TV series Indicator Problem

### ISSUE THREAD

**Issue by semool** [beatmasterRS/skin.arctic.zephyr.mod#936]
Something is wrong with this commit: https://github.com/beatmasterRS/skin.arctic.zephyr.mod/commit/773fb4ebf4181c6d38688cefabe0c141d44586f7

I have selected only New and watched in the Indicator config. This works fine before the commit.
Now i have the indicator running circle on every started TV Show and it replaced the new episodes indicator (flame)

**Comment by beatmasterRS** [comment]
I tried to change that. But I have a question of understanding. If I have a TV show that includes new eposides and some episodes are watched, I want to see the flame and not the in progress icon or? That means the flame always has priority, right?

**Comment by beatmasterRS** [comment]
Within the current PR, for me it seems to be fine. 

![screenshot01346](https://user-images.githubusercontent.com/3855273/224517257-15593996-8d8f-4718-bd17-2c4af51ebddf.png)

What do you think?

**Comment by beatmasterRS** [comment]
One more question: if I only have "New" and "Watched" enabled, no round circle would appear on "Marvel's Daredevil" as you can see on my screenshot (since in-progress is not enabled). Would it make sense to still show the round circle as a fallback in the list view to prevent empty fields? So that if I disable all options, I still get a round circle for all entries? Just a thought

**Comment by semool** [comment]
> If I have a TV show that includes new eposides and some episodes are watched, I want to see the flame and not the in progress icon or? That means the flame always has priority, right?

Yes i think that is the only logical Solution.

> Would it make sense to still show the round circle as a fallback in the list view to prevent empty fields? So that if I disable all options, I still get a round circle for all entries? Just a thought

No. Example: Myself i use a Widget in the Homescreen for Started Series. It displayed the Posters of my started Series. In the Widgets the status Icons would display as a Overlay in the Posters. I dont want any Overlays on this Posters (except the New flame), i know this was a running series :)

i will try the PR version now.

**Comment by beatmasterRS** [comment]
Okay thank you, then i will merge the pr :)
