### ISSUE TITLE
[Discussion] file "Custom_MovieSets.xml" does not exist ?

### ISSUE THREAD

**Issue by Nanomani** [beatmasterRS/skin.arctic.zephyr.mod#946]
In the xml code, there are references to the file "Custom_MovieSets.xml" which does not exist.

![2023-03-20_123232](https://user-images.githubusercontent.com/3939543/226328350-7f635592-5294-49b1-8841-9cf4874194d3.jpg)

You confirm that all the code related to this file is not useful?
Nothing pressing here. :)  
I m just curious

**Comment by beatmasterRS** [comment]
Yes, this code can safely be removed :)
