### ISSUE TITLE
Slight spelling and grammar issues

### ISSUE THREAD

**Issue by PSTrophy** [beatmasterRS/skin.arctic.zephyr.mod#99]
Just thought I would let you know on the Arctic Zephyr - Reloaded page under skin settings thaughts is spelt incorrectly and should be spelt 'thoughts' and the word on just before the web address should be 'at'. There's a few spelling mistakes in the change log for the skin also.

**Comment by beatmasterRS** [comment]
Thanks a lot, for pointing this out. I will take a look at the change log as well.

**Comment by PSTrophy** [comment]
Found a few more here's the list:

Skin settings/home - weather.widget.old could be 'Use old weather widget'
Under CleartArt both instances should be ClearLogo.

Skin settings/Colours - Userratings should be 'User ratings'
