### ISSUE TITLE
HOME SCREEN Skin Indicators missing when using FEN widgets

### ISSUE THREAD

**Issue by JesseNtaylor** [beatmasterRS/skin.arctic.zephyr.mod#999]
Hi I'm using Kodi 20.1 on Ubuntu 20.04 with Arctic zephyr reloaded as my skin, my video add on its now FEN (all latest versions)

I used to use Ezra and my home screen widgets would correctly show the Artic Zepher indicators from trakt such as "watched", "paused" etc in the top right corner correctly..

Since I switched back to Fen I've noticed the only home screenwidget indicators that show correctly are films and TV that are "PAUSED"

I've checked my watched status provider is Trakt inside fen settings and my skin indicator settings are all still correct, (but neither original or reloaded indicators work) my watched films DO NOT show any indicators on the home screen fen widgets..

If I go into the menus themselves instead of the widgets and change to any icon view the indicators are there fine, all of them ..

Just the home screen widgets are missing the indicators..

Here are my examples of trending movies.. one with the home screen widgets

![IMG_20230518_022019](https://github.com/beatmasterRS/skin.arctic.zephyr.mod/assets/101215194/43d385ab-9eb9-4a14-b4e7-850eb6d42f3f)

And one from the fen, movies, trending menus which DOES show correctly.. 

![IMG_20230518_022043](https://github.com/beatmasterRS/skin.arctic.zephyr.mod/assets/101215194/a05a5907-03bf-4f98-8efa-5efd78f082c5)

I've check with Tikipeter and he seems to think it's a skin issue not a FEN issue.. 

Can this be fixed?

Many thanks..

**Comment by beatmasterRS** [comment]
There is no support when illegal addons are used, sorry.
